### ISSUE TITLE
[v2 QUESTION]: About smiles sting with multiple fragamets

### ISSUE THREAD

**Issue by Rojina99** [chemprop/chemprop#1006]
I want to be able to encode smiles string like [Al].[OH2+]c1ccccc1 which can have any number of molecules or fragments in the smile string.

Can chemprop encode this information giving the information of whole smile string retaining the information of individual molecules without being redundant. Could you please point out how can i do it.

I do not want to train on two separate smile like this https://github.com/chemprop/chemprop/issues/906, here number of column seem to be fixed.

**Comment by shihchengli** [comment]
Hi, Chemprop is able to handle this kind of SMILES. We rely on the RDKit `rdkit.Chem.Mol` object to featurize a `MolGraph`. As long as your SMILES is valid, it shouldn't be a problem. Regardless you are using CLI or API, you don't need to do anything different than the task with SMILES containing only one fragment.

**Comment by Rojina99** [comment]
Thank you for your prompt response. I am wondering how would it differentiate fragments in the SMILES in algorithm ? I want to confirm that it represent all the fragments correctly also ensuring the information is not redundant i.e. just summing the individual molecules representation.

**Comment by shihchengli** [comment]
A SMILES string with multiple fragments is essentially a graph with subgraphs that lack edges between the fragments. That is said there is no message be passed across different fragments. If you want to verify whether your SMILES string represents the structure correctly as expected, you can try our [notebook](https://github.com/chemprop/chemprop/blob/main/docs/source/tutorial/python/data/datapoints.ipynb), which visualizes the molecular graph for a given SMILES. I'm not sure what you mean by summing the representations of individual molecules. For a D-MPNN with multiple components, the learned fingerprints are concatenated rather than summed. For a single graph, the information from each atomic embedding across all molecules is aggregated using the aggregation function chosen by the user (sum, mean, or norm). In the case of a SMILES string like `[Al].[OH2+]c1ccccc1`, it is just a graph and no different in the algorithm. I hope this is helpful.

**Comment by Rojina99** [comment]
Thank you very much.
