### ISSUE TITLE
[v2 BUG]: Passing parameters to metrics aren't considered at the end.

### ISSUE THREAD

**Issue by neuromaancer** [chemprop/chemprop#1081]
**Describe the bug**
Simplely, I have a multipout regression task, which I use R2 score. Naturally, I used the `nn.metrics.R2Score(multioutput="raw_values")` by passing `multioutput="raw_values"`, I expected the  output of R2Score in the test phase would be multiple R2.

**Example(s)**
This is what i put:
```py
metric_list = [
    nn.metrics.RMSE(),
    nn.metrics.MAE(),
    nn.metrics.R2Score(multioutput="raw_values"),
]
```
and I am truly my `y` is an array of 3 values. I dive into to source code `chemprop/models/model.py` around line 93 and put:
```py
self.metrics = (
            nn.ModuleList([*metrics, self.criterion.clone()])
            if metrics
            else nn.ModuleList([self.predictor._T_default_metric(), self.criterion.clone()])
        )
        print("I am here==============================")
        print(self.metrics) 
```

The output is 
```sh
I am here==============================
ModuleList(
  (0): RMSE(task_weights=[[1.0]])
  (1): MAE(task_weights=[[1.0]])
  (2): R2Score()
  (3): MSE(task_weights=[[1.0, 1.0, 1.0]])
)
```

Apparently, the package didn't take the parameter I passed to R2Score.

**Environment**
- python version 3.12
- package versions: chemprop. 2.1.0
- MacOS

**Checklist**
- [x] all dependencies are satisifed: `conda list` or `pip list` shows the packages listed in the `pyproject.toml`
- [x] the unit tests are working: `pytest -v` reports no errors

**Comment by KnathanM** [comment]
What do you get if you do `print(self.metrics[2].multioutput)`? I think `lightning`'s `R2Score` `__repr__` method doesn't show this attribute even if it is different than the default.

**Comment by neuromaancer** [comment]
> What do you get if you do `print(self.metrics[2].multioutput)`? I think `lightning`'s `R2Score` `__repr__` method doesn't show this attribute even if it is different than the default.

print(self.metrics[2].multioutput) return "raw_values", but my target is an array of 3 different value, I only get one r2, which is a different behavior using `sklearn` r2 function. Sklearn gives me 3 different ones.

**Comment by neuromaancer** [comment]
For example, below is my one data point:
```sh
MoleculeDatapoint(mol=<rdkit.Chem.rdchem.Mol object at 0x7d86ce13a810>, y=array([19.3,  7.7,  5.9]), weight=1.0, gt_mask=None, lt_mask=None, x_d=None, x_phase=None, name='O(P(=O)(OC1=CC=C(C=C1)C)OC2=CC=C(C=C2)C)C3=CC=C(C)C=C3', V_f=None, E_f=None, V_d=None)
```
I have add `num_outputs=3` to R2Score class, it can give me 3 numbers but they all the same:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test/mae          │    0.7890576124191284     │
│          test/r2          │   [0.9262351989746094,    │
│                           │    0.9262351989746094,    │
│                           │    0.9262351989746094]    │
│         test/rmse         │    1.8080382347106934     │
└───────────────────────────┴───────────────────────────┘
with the following error message:
`ValueError: The metric `tensor([0.9262, 0.9262, 0.9262], device='cuda:0')` does not contain a single element, thus it cannot be converted to a scalar.`

**Comment by KnathanM** [comment]
Looks like there are two problems here:

First in the `MPNN` class we pass the metric instance to be logged as [recommended](https://lightning.ai/docs/torchmetrics/stable/pages/lightning.html#torchmetrics-in-pytorch-lightning) by `torchmetrics`:
https://github.com/chemprop/chemprop/blob/bf00b3907121ec4ac982d48efb991f2646729b90/chemprop/models/model.py#L188
If the metric returns a non-scalar tensor, `torchmetrics`  [says](https://lightning.ai/docs/torchmetrics/stable/pages/lightning.html#torchmetrics-in-pytorch-lightning) the metric "should ... be dealt with separately". This seems more like a problem on `torchmetrics` end as I would expect their logger to be able to handle when a metric returns a non-scalar tensor. You could open an issue on their GitHub. I'm not sure what a good fix on the `chemprop` side would be, but it would require something like this [in](https://github.com/chemprop/chemprop/blob/bf00b3907121ec4ac982d48efb991f2646729b90/chemprop/models/model.py#L175) `_evaluate_batch()`:
```
for m in self.metrics[:-1]:
    loss = m(preds, targets, mask, weights, lt_mask, gt_mask)
    try:
        self.log(f"{label}/{m.alias}", m, batch_size=len(batch[0]))
    except:
        for j in loss.shape[1]:
            self.log(f"{label}/{m.alias}/task_{j}", loss[:, j], batch_size=len(batch[0])) 
```

The second problem is that all the outputs of R2Score are the same. This happens because we try to automatically [mask](https://github.com/chemprop/chemprop/blob/bf00b3907121ec4ac982d48efb991f2646729b90/chemprop/models/model.py#L178) out `nan` values in `targets` so that a user could give incomplete training data. In [R2Score](https://github.com/chemprop/chemprop/blob/bf00b3907121ec4ac982d48efb991f2646729b90/chemprop/nn/metrics.py#L177) we do: `targets[mask]` which has the unintended effect of reducing targets to a [1D tensor](https://stackoverflow.com/questions/76899204/pytorch-tensor-loss-of-dimension-when-masking). Looks like what we actually want is a `MaskedTensor`, but that isn't [available yet](https://pytorch.org/tutorials/prototype/maskedtensor_overview) best I can tell. 

If you are just trying to get the R2 score for a test set, I recommend using `trainer.predict` to get the predictions and then use `torchmetrics.R2Score`:
```
preds = torch.concat(trainer.predict(model, test_loader), 0)
targets = torch.tensor(test_loader.dataset.Y)
metric = torchmetrics.R2Score(multioutput="raw_values", num_outputs=4)
metric(preds, targets)
```

**Comment by abazabaaa** [comment]
I think that I am having a related issue.

env (rhel8, uv env with lockfile) I can put the whole lock file in but its long.:
```
[project]
name = "foobar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.10"
dependencies = [
    "chemprop>=2.1.0",
    "ray[tune]>=2.38.0",
    "internalpackage>=2.3.4",
    "tensorboard>=2.18.0",
]
```

After hyperparam optimization with the CLI I get the following config:
```
smiles-columns = [smiles]
num-workers = 15
data-path = data.csv
output-dir = output_train_post_hyperparam_opt
target-columns = [col1, col2, col3]
task-type = regression
loss-function = mse
#metrics = r2
num-replicates = 5
save-smiles-splits = true
data-seed = 0
pytorch-seed = 0
batch-size = 64
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 2400
depth = 5
dropout = 0.35000000000000003
activation = RELU
aggregation = norm
aggregation-norm = 100
ffn-hidden-dim = 300
ffn-num-layers = 1
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
warmup-epochs = 23
init-lr = 0.0003838541689337728
max-lr = 0.009987112293990507
final-lr = 0.00010550747971524468
epochs = 50
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
```

Running the train CLI with
```
CUDA_VISIBLE_DEVICES=4,5,6,7 uv run chemprop train \
         --config-path best_config.toml \
         -v
```

During the run I see the following config reported:
```
2024-10-24T17:43:10 - INFO:chemprop.cli.main - Running in mode 'train' with args: {'smiles_columns': ['smiles'], 'reaction_columns': None, 'no_header_row': False, 'num_workers': 15, 'batch_size': 64, 'accelerator': 'auto', 'devices': 'auto', 'rxn_mode': 'REAC_DIFF', 'multi_hot_atom_featurizer_mode': 'V2', 'keep_h': False, 'add_h': False, 'molecule_featurizers': None, 'descriptors_path': None, 'no_descriptor_scaling': False, 'no_atom_feature_scaling': False, 'no_atom_descriptor_scaling': False, 'no_bond_feature_scaling': False, 'atom_features_path': None, 'atom_descriptors_path': None, 'bond_features_path': None, 'config_path': PosixPath('best_config.toml'), 'data_path': PosixPath('data.csv'), 'output_dir': PosixPath('output_train_post_hyperparam_opt'), 'remove_checkpoints': False, 'checkpoint': None, 'freeze_encoder': False, 'model_frzn': None, 'frzn_ffn_layers': 0, 'ensemble_size': 1, 'message_hidden_dim': 2400, 'message_bias': False, 'depth': 5, 'undirected': False, 'dropout': 0.35000000000000003, 'mpn_shared': False, 'activation': 'RELU', 'aggregation': 'norm', 'aggregation_norm': 100.0, 'atom_messages': False, 'ffn_hidden_dim': 300, 'ffn_num_layers': 1, 'batch_norm': False, 'multiclass_num_classes': 3, 'weight_column': None, 'target_columns': ['col1', 'col2', 'col3'], 'ignore_columns': None, 'no_cache': False, 'splits_column': None, 'task_type': 'regression', 'loss_function': 'mse', 'v_kl': 0.0, 'eps': 1e-08, 'alpha': 0.1, 'metrics': ['r2'], 'tracking_metric': 'val_loss', 'show_individual_scores': False, 'task_weights': None, 'warmup_epochs': 23, 'init_lr': 0.0003838541689337728, 'max_lr': 0.009987112293990507, 'final_lr': 0.00010550747971524468, 'epochs': 50, 'patience': None, 'grad_clip': None, 'class_balance': False, 'split': 'RANDOM', 'split_sizes': [0.8, 0.1, 0.1], 'split_key_molecule': 0, 'num_replicates': 5, 'num_folds': None, 'save_smiles_splits': True, 'splits_file': None, 'data_seed': 0, 'pytorch_seed': 0}
```

However in the debug I see:
```
2024-10-24T17:43:17 - DEBUG:chemprop.cli.train - Evaluation metric: 'mse', mode: 'min'
```

And I see the following for the model params:
```
2024-10-24T17:43:17 - INFO:chemprop.cli.train - MPNN(
  (message_passing): BondMessagePassing(
    (W_i): Linear(in_features=86, out_features=2400, bias=False)
    (W_h): Linear(in_features=2400, out_features=2400, bias=False)
    (W_o): Linear(in_features=2472, out_features=2400, bias=True)
    (dropout): Dropout(p=0.35000000000000003, inplace=False)
    (tau): ReLU()
    (V_d_transform): Identity()
    (graph_transform): GraphTransform(
      (V_transform): Identity()
      (E_transform): Identity()
    )
  )
  (agg): NormAggregation()
  (bn): Identity()
  (predictor): RegressionFFN(
    (ffn): MLP(
      (0): Sequential(
        (0): Linear(in_features=2400, out_features=300, bias=True)
      )
      (1): Sequential(
        (0): ReLU()
        (1): Dropout(p=0.35000000000000003, inplace=False)
        (2): Linear(in_features=300, out_features=3, bias=True)
      )
    )
    (criterion): MSE(task_weights=[[1.0, 1.0, 1.0]])
    (output_transform): UnscaleTransform()
  )
  (X_d_transform): Identity()
  (metrics): ModuleList(
    (0): R2Score()
    (1): MSE(task_weights=[[1.0, 1.0, 1.0]])
  )
)
```

Then I get this warning:
```
/prj/xxxxx/chemprop2_jobs/xxxxx/.venv/lib/python3.11/site-packages/lightning/pytorch/core/saving.py:363: Skipping 'metrics' parameter because it is not possible to safely dump to YAML.
```

Then after one round of 50 epochs the following error is thrown:
```
[rank2]: 	Unexpected key(s) in state_dict: "metrics.0.task_weights".
[rank0]: Traceback (most recent call last):
[rank0]:   File "/prj/xxxxx/chemprop2_jobs/xxxxx/.venv/bin/chemprop", line 8, in <module>
[rank0]:     sys.exit(main())
[rank0]:              ^^^^^^
[rank0]:   File "/prj/xxxxx/chemprop2_jobs/xxxxx/.venv/lib/python3.11/site-packages/chemprop/cli/main.py", line 85, in main
[rank0]:     func(args)
[rank0]:   File "/prj/xxxx/chemprop2_jobs/xxxxx/.venv/lib/python3.11/site-packages/chemprop/cli/train.py", line 89, in func
[rank0]:     main(args)
[rank0]:   File "/prj/xxxxx/chemprop2_jobs/xxxxxx/.venv/lib/python3.11/site-packages/chemprop/cli/train.py", line 1321, in main
[rank0]:     train_model(
[rank0]:   File "/prj/xxxxx/xxxx/xxxxx/.venv/lib/python3.11/site-packages/chemprop/cli/train.py", line 1153, in train_model
[rank0]:     model = model.load_from_checkpoint(best_ckpt_path)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/prj/xxxx/chemprop2_jobs/xxxx/.venv/lib/python3.11/site-packages/chemprop/models/model.py", line 292, in load_from_checkpoint
[rank0]:     return super().load_from_checkpoint(buffer, map_location, hparams_file, strict, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/prj/xxxx/chemprop2_jobs/xxx/.venv/lib/python3.11/site-packages/lightning/pytorch/utilities/model_helpers.py", line 125, in wrapper
[rank0]:     return self.method(cls, *args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/prj/xxxx/chemprop2_jobs/xxxx/.venv/lib/python3.11/site-packages/lightning/pytorch/core/module.py", line 1582, in load_from_checkpoint
[rank0]:     loaded = _load_from_checkpoint(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/prj/xxx/chemprop2_jobs/xxx/.venv/lib/python3.11/site-packages/lightning/pytorch/core/saving.py", line 91, in _load_from_checkpoint
[rank0]:     model = _load_state(cls, checkpoint, strict=strict, **kwargs)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/prj/xxx/chemprop2_jobs/xxxx/.venv/lib/python3.11/site-packages/lightning/pytorch/core/saving.py", line 187, in _load_state
[rank0]:     keys = obj.load_state_dict(checkpoint["state_dict"], strict=strict)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/prj/xxxx/chemprop2_jobs/xxxx/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
[rank0]:     raise RuntimeError(
[rank0]: RuntimeError: Error(s) in loading state_dict for MPNN:
[rank0]: 	Unexpected key(s) in state_dict: "metrics.0.task_weights".
```

After several tries at this I concluded that the CLI was not respecting the evaluation metric argument.  If I simply remove the r2 value as the desired validation metric it seems to work fine. Is this the expected behavior?

**Comment by KnathanM** [comment]
@abazabaaa That issue is related, but different enough to warrant a separate issue. Can you open a new issue with "Unexpected key(s) in state_dict: 'metrics.0.task_weights'" as part of the title? I'll look into it.

@neuromaancer Glad my suggestion worked for you. There could be many reasons the score is not that high, including model hyperparameters, data representation/featurization, data distributions, and whether D-MPNNs are suitable to begin with. If you have further issues running the chemprop code, please reach out again.

**Comment by neuromaancer** [comment]
> @abazabaaa That issue is related, but different enough to warrant a separate issue. Can you open a new issue with "Unexpected key(s) in state_dict: 'metrics.0.task_weights'" as part of the title? I'll look into it.
> 
> @neuromaancer Glad my suggestion worked for you. There could be many reasons the score is not that high, including model hyperparameters, data representation/featurization, data distributions, and whether D-MPNNs are suitable to begin with. If you have further issues running the chemprop code, please reach out again.

Thank you for the information. I think the problem in the original R2Score in `chemprop` do a flattening predictions before the calculation, so the score is higher than separation of calculation for different regression targets.
