### ISSUE TITLE
parameterized missing in install requirements

### ISSUE THREAD

**Issue by davidxmarcus** [chemprop/chemprop#132]
Please add to install_requires: 'parameterized>=0.8.1' missing in the setup.py

Thanks,
David.

**Comment by davidxmarcus** [comment]
Also update setup.py for 'scipy>=1.4.1'

**Comment by swansonk14** [comment]
Hi @davidxmarcus, thank you for the suggestions! I went ahead and changed the scipy version from `scipy==1.4.1` to `scipy>=1.4.1` in this commit: https://github.com/chemprop/chemprop/commit/d051d557c7c85ee0057ac5e50fface55d2f07930. Since `parameterized` is only needed when running tests, we decided not to add it to `install_requires`. Instead, we've moved it to `extras_require` so that you can install those requirements with `pip install -e .[test]`. I hope this helps!
