### ISSUE TITLE
Incorrect behavior for atom_messages = True

### ISSUE THREAD

**Issue by Varal7** [chemprop/chemprop#133]
I think there is currently a bug where args.atom_messages = True.
BatchMolGraph uses the get_bond_dim() function without forwarding the argument which seems will lead to incorrect dimension of the bond features.

**Comment by fhvermei** [comment]
The bond feature vector in BatchMolGraph are indeed constructed using both the atom and bond features. When the bond feature vector is called for the MPNN (BatchMolGraph.get_components(atom_messages=True)) the size of the bond feature vector is corrected and the atom features are removed.

**Comment by Varal7** [comment]
I am talking about this line: https://github.com/chemprop/chemprop/blob/8258fcbea2bc4bd22889ba284389382ced97ae61/chemprop/features/featurization.py#L206

But I can run some tests tomorrow and submit a proper bug report if needs be

**Comment by hesther** [comment]
Thank you for your question! Just had a look - I agree with Florence. Upon initialising BatchMolGraph, the bond dimensions are set up alike no matter whether atom messages are used or not  (line 206), and the bond features are set up with the full vector (bond + atom features). But when returning the atom and bond features in `get_components`, the bond features get truncated up to their correct length if atom messages are used (with the length determined by calling `get_bond_fdim` again with `atom_messages=True`):

https://github.com/chemprop/chemprop/blob/8258fcbea2bc4bd22889ba284389382ced97ae61/chemprop/features/featurization.py#L246-L272

This may be a bit clumsy (and there might be faster ways to do this), but correct.

I will close this issue for now, but please feel free to reopen if you have further questions! Yours, Esther

**Comment by hesther** [comment]
While looking through the code more thoroughly today, I noticed that there actually IS a bug (although a different one than reported):

We set up the bond features in the order atom(length 133)-bond(length 14):

https://github.com/chemprop/chemprop/blob/8258fcbea2bc4bd22889ba284389382ced97ae61/chemprop/features/featurization.py#L171-L172

but then cut out the first (!) 14 values, instead of the last:

https://github.com/chemprop/chemprop/blob/8258fcbea2bc4bd22889ba284389382ced97ae61/chemprop/features/featurization.py#L267-L270

Can someone else confirm this, so I can write a PR?

**Comment by cjmcgill** [comment]
@hesther It looks this way to me as well
