### ISSUE TITLE
Prediction with more than 20 Million molecules

### ISSUE THREAD

**Issue by matany58** [chemprop/chemprop#142]
I am using the prediction script ( predict.py) to run a prediction with more than 20 million compounds, it is taking  several days to run (running it on a GPU).
Please which option can I choose to make it run faster?

Thanks for your assistance.

**Comment by cjmcgill** [comment]
I am not sure which part of the program is coming under strain with the 20 million molecules. It may be the initial data import but it could be lots of things.

For a prediction, there is not much efficiency gain from running many molecules instead of just a few. And in your case it may be creating new bottlenecks. I would recommend breaking the 20 million into more manageable chunks (maybe 10k or so) and then running those through separately.

**Comment by matany58** [comment]
Yes the part of the program coming under strain is the initial data import for the 20 million molecules  for the prediction. Is there a way it could be imported/uploaded faster for the model use?

**Comment by cjmcgill** [comment]
Your best bet is going to be to separate your molecules into chunks of 10k or so. Especially if your gpu is working appropriately, each individual chunk will go pretty fast.
