### ISSUE TITLE
Request to add class weights and sample weights

### ISSUE THREAD

**Issue by jasonzdeng** [chemprop/chemprop#145]
Hi, has there been any near-future plan or thoughts to add class weights and sample weights into chemprop? Thanks!

**Comment by hesther** [comment]
Hi @jasonzdeng , sorry for the late response, it took us quite a while to come up with a plan of which features are going to be included next. The class and sample weights option has made it on our todo-list, but will probably not be implemented before summer, or even fall.

Meanwhile, if you are looking to improve training in case of unequally populated classes, you can use the argument `--class_balance` to at least produce balanced training batches. I know, this is not directly what you were asking for, but might be helpful to know.

**Comment by hesther** [comment]
Hi @jasonzdeng,
In a recent PR (#173 and #175) we introduced target weights and data point weights. I am copying the respective section from the README below, hope this is useful to you! I will close this issue, since I guess it is solved, but feel free to reopen if you feel it isn't!

============================
By default, each task in multitask training and each provided datapoint are weighted equally for training. Weights can be specified in either case to allow some tasks in training or some specified data points to be weighted more heavily than others in the training of the model.

Using the `--target_weights` argument followed by a list of numbers equal in length to the number of tasks in multitask training, different tasks can be given more weight in parameter updates during training. For instance, in a multitask training with two tasks, the argument `--target_weights 1 2` would give the second task twice as much weight in model parameter updates.

Using the `--data_weights_path` argument followed by a path to a data file containing weights will allow each individual datapoint in the training data to be given different weight in parameter updates. Formatting of this file is similar to provided features CSV files: they should contain only a single column with one header row and a numerical value in each row that corresponds to the order of datapoints provided with `--data_path`. Data weights do not need to be provided for validation or test sets if they are provided through the arguments `--separate_test_path` or `--separate_val_path`.
