### ISSUE TITLE
Transfer learning of the chemprop

### ISSUE THREAD

**Issue by ismorphism** [chemprop/chemprop#156]
Hello everyone and the amazing team of chemprop creators! :-) 
Is it possible to implement finetuning of the chemprop model and include it in the package? To freeze the neural net layers in the training phase? Sometimes we have necessity to use finetuning in the tasks like logP/D prediction and many others

**Comment by cjmcgill** [comment]
Hi @ismorphism , thanks this is a great suggestion. Frozen layers for fine-tuning or transfer learning has been something different developers have been doing for a while and is on our list of things we want to add to the repository in the future. 

I am reading your suggestion as wanting to read all the weights from checkpoint files and freeze the message passing weights while allowing the FFN weights to be further optimized. In my conception on this, I think we would also want the option to reinitialize the FFN weights from scratch for more of a transfer learning application. Am I understanding your suggestion properly? Are there any other options that would be beneficial for you?

If you need a short term solution, please ask and I may be able to provide you with the lines of code to implement it.

**Comment by ismorphism** [comment]
Thank you for your quick response! ❤️  You're right about the description of fine-tuning for the case and I thought exactly this way - to use pretrained weights of MPN and retrain the FFN weights. 

`
model = load_checkpoint("PATH_2_MODEL")
MPN_last = amount of MPN layers
for layer in model.layers[:MPN_last]:
    layer.is_trainable = False
`

It is smth what comes frist in my mind in analogy with TensorFlow way.

**Comment by hesther** [comment]
Hi @ismorphism ,
In a recent PR (#170) we introduced more options for pertaining and transfer learning (freezing layers). I am copying the respective part from the README below. I hope this is of help!

=======================================
Pretraining can be carried out using previously trained checkpoint files to set some or all of the initial values of a model for training. Additionally, some model parameters from the previous model can be frozen in place, so that they will not be updated during training.

Pretraining can be carried out using previously trained checkpoint files to set some or all of the initial values of a model for training. Additionally, some model parameters from the previous model can be frozen in place, so tha
t they will not be updated during training.

Parameters from existing models can be used for parameter-initialization of a new model by providing a checkpoint of the existing model using either
 * `--checkpoint_dir <dir>` Directory where the model checkpoint(s) are saved (i.e. `--save_dir` during training of the old model). This will walk the directory, and load all `.pt` files it finds.
 * `--checkpoint_path <path>` Path to a model checkpoint file (`.pt` file).
 * `--checkpoint_paths <list of paths>` A list of paths to multiple model checkpoint (`.pt`) files.
when training the new model. The model architecture of the new model should resemble the architecture of the old model - otherwise some or all parameters might not be loaded correctly. If any of these options are specified during training, any argument provided with `--ensemble_size` will be overwritten and the ensemble size will be specified as the number of checkpoint files that were provided, with each submodel in the ensemble using a separate checkpoint file for initialization. When using these options, new model parameters are initialized using the old checkpoint files but all parameters remain trainable (no frozen layers from these arguments).

Certain portions of the model can be loaded from a previous model and frozen so that they will not be trainable, using the various frozen layer parameters. A path to a checkpoint file for frozen parameters is provided with the argument `--checkpoint_frzn <path>`. If this path is provided, the parameters in the MPNN portion of the model will be specified from the path and frozen. Layers in the FFNN portion of the model can also be applied and frozen in addition to freezing the MPNN using `--frzn_ffn_layers <number-of-layers>`. Model architecture of the new model should match the old model in any layers that are being frozen, but non-frozen layers can be different without affecting the frozen layers (e.g., MPNN alone is frozen and new model has a larger number of FFNN layers). Parameters provided with `--checkpoint_frzn` will overwrite initialization parameters from `--checkpoint_path` (or similar) that are frozen in the new model. At present, only one checkpoint can be provided for the `--checkpoint_frzn` and those parameters will be used for any number of submodels if `--ensemble_size` is specified. If multiple molecules (with multiple MPNNs) are being trained in the new model, the default behavior is for both of the new MPNNs to be frozen and drawn from the checkpoint. Only the first MPNN will be frozen and subsequent MPNNs still allowed to train if `--freeze_first_only` is specified.

**Comment by hesther** [comment]
Am closing this since I think it was solved - feel free to reopen!
