### ISSUE TITLE
predicting on a single task overwrite existing columns

### ISSUE THREAD

**Issue by eyalmazuz** [chemprop/chemprop#174]
I have 2 CSV files that contain the following columns: Drug1_SMILES, Drug2_SMILES, label
one is the train-set and the other is the test-set, when training the model the task name is called label because this is the target column.

but when using `--save_preds` or `chemprop_predict` on the test-set because the task name is set to "label" it overwrites the existing labels in the newly created CSV file.
is there a way to make it not overwrite the existing label column by renaming the columns where the predictions will be stored?
if not I think it would be a nice addition to the code.

**Comment by cjmcgill** [comment]
So you would like the original target and the prediction to both be saved in the predictions file?

**Comment by eyalmazuz** [comment]
yes, because the column named "label" contained the ground truth of the test set, I would like the predictions of the model to be stored in a new column named for example: "predictions",  instead of having the predictions under the "label" column which overwrites the ground truth column in the generated CSV file

**Comment by hesther** [comment]
Hi @eyalmazuz, this is currently not an option in Chemprop, however, you can easily help yourself via renaming the column in your test set CSV file to e.g. `Drug1_SMILES, Drug2_SMILES, label_true`, in which case the output CSV will have four columns, `Drug1_SMILES, Drug2_SMILES, label_true, label` where "label" is the predicted label and "label_true" the actual label.

**Comment by hesther** [comment]
I think (?) this issue was resolved, so am closing it, but feel free to reopen if necessary! I think manually renaming the columns in a test file is more convenient than supplying an extra option, and also saves disk space - if you already have a separate test file, why save the true values again to file? However, I also see why this was requested in the first place, and would be happy to implement this option if we decide we need it.
