### ISSUE TITLE
"Aromatic bond on non aromatic atom 0" during interpretation

### ISSUE THREAD

**Issue by goolig** [chemprop/chemprop#178]
I have a trained model which produced predictions however it fails for interpretation for several drugs. Here is the error message.
![image](https://user-images.githubusercontent.com/11397146/121855373-ee315480-ccfb-11eb-9c1d-2947c60807a2.png)

I get it for the drug Fiacitabine, Smiles:
NC1=NC(=O)N(C=C1I)[C@@H]1O[C@H](CO)[C@@H](O)[C@@H]1F

Looks like the problem is with rdkit, however, I am not sure what exactly is the reason, I get a normal prediction for this drug.

Command used:
chemprop_interpret --data_path data.csv --checkpoint_dir cp/fold_0 --features_generator rdkit_2d_normalized --no_features_scaling --property_id 1 --smiles_column Smiles

**Comment by hesther** [comment]
Dear @goolig, the interpretation script extracts subgraphs from a molecule which contribute most to the observed property. It seems like one of the extracted subgraphs contains half of an aromatic ring (but not the rest of the ring), which causes an error with rdkit (saying that a partial ring cannot be aromatic). This does not affect the prediction in any way, it is just the interpretation script that will error out (in detail, no RDKit molecule of the subgraph can be made, and thus the subgraph cannot be transformed to a SMILES string and printed to file).

I need to look into the problem more to suggest a fix - possible options would be to print substructures as SMARTS not SMILES, use SMILES but without sanitising the molecule, or to include a whole ring instead of just a part - which all have aspects that are a bit undesirable. I will run some tests.

**Comment by hesther** [comment]
Dear @goolig, it seems like some versions of rdkit do not return None if Chem.MolToSmiles() does not come to a result but instead raise an exception. This change was introduced in rdkit 2021.03.01. As a quick fix, you could downgrade your rdkit installation (e.g. to rdkit 2020.xxxx or 2019.xxxx). We will work on a general fix in the code, soon.

**Comment by goolig** [comment]
Thank you! Downgrading rdkit worked for me.

**Comment by hesther** [comment]
Just added a general fix in the code, thanks again for reporting!
