### ISSUE TITLE
Cannot get the Antibiotics stock model to work following the intructions included in the Readme

### ISSUE THREAD

**Issue by Jblauvs** [chemprop/chemprop#180]
I'm trying to get Chemprop to work with the stock models but am having difficulty.  I ran the command supplied with the Antibiotics model. 

Instructions supplied with the model :

# Trained Chemprop Antibiotics Model

Code: https://github.com/swansonk14/chemprop

This directory contains an ensemble of 20 trained antibiotics models. To make predictions using this ensemble, download and install Chemprop (use the link above), then run:

```
python predict.py --test_path /path/to/molecules.csv --preds_path /path/to/predictions.csv --checkpoint_dir /path/to/this/directory --config_path /path/to/this/directory/0406_inhibition_hyperopt.json --features_generator rdkit_2d_normalized --no_features_scaling
```

I install Chemprop from source, I have also tried using pypi, and then run the command above and receive the following error:

```
predict.py: error: unrecognized arguments: --config_path /path/to/this/directory/0406_inhibition_hyperopt.json
```

Then I remove the offending line and get this error:

```
ValueError: Features were used during training so they must be specified again during prediction using the same type of features as before (with either --features_generator or --features_path and using --no_features_scaling if applicable).
```

I get that same error when trying to use the make_predictions function within a script, as the supplied flask app does.

**Comment by Jblauvs** [comment]
I am injecting my own paths where specified, for reference.

**Comment by hesther** [comment]
Hi @Jblauvs, it seems like the README didn't get updated yet after a couple of changes in the software. A recent update demands features to be created the exact same way during training and prediction. Since during training, the features were precomputed and saved to file, you need to do the same during prediction:

`python scripts/save_features.py --data_path /path/to/molecules.csv --save_path /path/to/smiles_features.npz --features_generator rdkit_2d_normalized`

which will create a new file with molecular features (`/path/to/smiles_features.npz`)

Then run:
`python predict.py --test_path /path/to/molecules.csv  --checkpoint_dir /path/to/this/directory --preds_path /path/to/predictions.csv --features_path /path/to/smiles_features.npz  --no_features_scaling`

Let me know if you have any further problems, and I apologise for this inconvenience.

**Comment by Jblauvs** [comment]
Hey @hesther I was able to get it to work as you described.  Thanks for the prompt response!
