### ISSUE TITLE
mixture embeddings?

### ISSUE THREAD

**Issue by byooooo** [chemprop/chemprop#181]
Hi,

Is it possible to use chemprop to generate embeddings for multicomponent systems? For instance, if I have a 2-component system (e.g., 'CCCCC' and 'COCCOCCOCCOCC') at 50/50 mole fraction and a corresponding target property, i'd like to generate MPNN embeddings for both component 1 and component 2 and take the mole fraction weighted average of these embeddings as the final embedding step.

Any advice would be greatly appreciated!

**Comment by hesther** [comment]
Dear @byooooo, we do use models just like what you described for our research projects, and I will ask whether they are publicly available already (or else provide you with some suggestions on how to do that) - it is definitely doable (and works well). I will get back to you.

**Comment by byooooo** [comment]
Thanks @hesther! Either solution sounds great.

So far I've just played around with the `chemprop.features.MolGraph()` and `chemprop.rdkit.make_mol()` functionality on separate SMILES, but got a little lost in getting the output into the MPNN Encoder.

**Comment by hesther** [comment]
Dear @byooooo, our mixture research projects are still in progress, so the models are not available yet (and might not be for a few months). You of course may choose to wait for it, it is certainly on our todo-list. If you want to try yourself in the meanwhile, I can give you some implementation option based on what you are looking for in detail. There are some code fragments on multi-molecule input (in the main chemprop project), as well as input of  reactant/product pairs (in a different repo I can send you a link for) that you could build on.

Based on your answer to the following questions I can point you in the right direction.
- What is the structure of your data? Is it always binary mixtures, or possibly more than two components? The current multi-molecule input would provide you with a flexible input.
- Do you want a shared or separate MPNNs for encoding the parts of the mixture? That is, are the parameters of the MPNN the same for each component? I would recommend that, since it makes your input invariant to permutation, i.e. 40% water 60% ethanol would give the same prediction as 60% ethanol 40% water. If your mixture components have different "roles", like primary solvent and an impurity, you might instead want to use separate MPNNs.
- Do you want to use additional molecular features? If not, it might be very easy to do a quick-and-dirty implementation by mis-using the molecular feature data for storing mole fractions together with the already existing multi-molecule input option.

In general, you would probably make most changes in chemprop/models/mpn.py in the MPN class, towards the end of the forward() function

**Comment by byooooo** [comment]
Thanks @hesther. Here's my answers to your questions:


- **What is the structure of your data? Is it always binary mixtures, or possibly more than two components? The current multi-molecule input would provide you with a flexible input.**

At the moment, my dataset only contains binary mixtures of polymer/polymer or polymer/solvent and also has a hierarchical structure to it:

lower level: SMILES of polymer building blocks for compound 1 + SMILES of polymer building blocks for compound 2
middle level: number of units for each polymer building block
higher level: mixing ratios of the two

Example: polymer 1 contains SMILES: {CCC*:1, \*COC*:10, CCC* :1} where 1, 10, and 1 correspond to the counts of each SMILES

For this specific dataset, I've broken down each polymer SMILES into head + tail + repeat unit SMILES (i.e., fragments) since theyre all linear chains, but I can also have binary mixtures of a single polymer with a solvent containing 1 SMILES. I don't intend to preserve topology. So in some sense, it could be thought of as a multicomponent mixture beyond binary blends.

- **Do you want a shared or separate MPNNs for encoding the parts of the mixture? That is, are the parameters of the MPNN the same for each component? I would recommend that, since it makes your input invariant to permutation, i.e. 40% water 60% ethanol would give the same prediction as 60% ethanol 40% water. If your mixture components have different "roles", like primary solvent and an impurity, you might instead want to use separate MPNNs.**

I was also thinking about sharing the MPNN, but naively thought I could first generate the MPNN embeddings for each building block separately, then just combine them by taking weighted averages in latent space based on the corresponding number of building block and mixing ratios. I think this should make it invariant to permutation. Of course, I'm open to any suggestions/ideas!

- **Do you want to use additional molecular features? If not, it might be very easy to do a quick-and-dirty implementation by mis-using the molecular feature data for storing mole fractions together with the already existing multi-molecule input option.**

Yep, I have additional features such as temperature, MWs, and possibly traditional RDKit descriptors that I'd also like to concatenate.

This hierarchical weighted averaging also seems to work well if I just use traditional descriptors, but I wanted to see if the MPNN can achieve better performance.

Hope this clarifies things!

**Comment by hesther** [comment]
This seems like a good candidate to build off of the current multi-molecule model. If you have a newish (less than a few months old) version of chemprop you should be able to input multiple molecules, comma-separated, here for 2 molecules for example (but it works with any number):

```
smiles1,smiles2,target
CC,CCC,0.3
CCC,CCO,0.5
C,CCCCO,0.9
CC,CCC,0.3
CCC,CCO,0.5
C,CCCCO,0.9
CC,CCC,0.3
CCC,CCO,0.5
C,CCCCO,0.9
CC,CCC,0.3
CCC,CCO,0.5
C,CCCCO,0.9
```
and train a model via
`python train.py --dataset_type regression --data_path test.csv --number_of_molecules 2`
(which makes separate MPNNs for each molecule), or
`python train.py --dataset_type regression --data_path test.csv --number_of_molecules 2 --mpn_shared`
(which makes one shared MPNN for all molecules)
If you look at the terminal output, you can see that their architecture is exactly the same, but option 2 has much less trainable parameters, because the weights of the two MPNNs are forced to be equal. 

Currently, the output of the two MPNNs (or generally for any number of MPNNs) is concatenated and passed to the feed forward NN readout. You will instead want to compute weighted averages. So, you will need to change [line 258 in chemprop/models/mpn.py](https://github.com/chemprop/chemprop/blob/eaa06b3318eed600ee4ebdb7fbf368277f27930e/chemprop/models/mpn.py#L258) which concatenates the embeddings of the molecules. Make sure to make all changes before the molecular features are concatenated in line 260. To read in your mole fractions you will need to create an object similar to `features_batch` which you can pass to the `forward` function of the MPN class. I suggest you start with hard-coding a ratio (e.g. 0.5) to get started, and check all the dimensions of your model diligently, and then add the correct ratios once that works. For reading in ratios, you should be able to copy-paste most of the functions for reading molecular features via the` --features_path` option.

**Comment by byooooo** [comment]
Perfect! thank you very much @hesther! This seems pretty straight forward to modify. Will definitely test this out!

**Comment by hesther** [comment]
Happy to help! Let me know how it worked out, and feel free to reopen the issue or open a new one as needed!

**Comment by byooooo** [comment]
Hi @hesther, just as an update, I was able to implement the changes you suggested in my forked repo https://github.com/byooooo/chemprop. Thanks a lot for the help and insight into the code! 😄

**Comment by hesther** [comment]
Hi @byooooo, great to hear, I am glad it worked out!
