### ISSUE TITLE
Binary systems

### ISSUE THREAD

**Issue by hb563** [chemprop/chemprop#196]
I am trying to understand how to add features for a binary system. For example, if I wanted to include the mole fractions of each molecule for a given target, how should the data be ordered?

**Comment by hesther** [comment]
Just to make sure I understand your question correctly, that would be data like 30% methanol and 70% ethanol has a target of 0.8, 50% methanol and 50% ethanol has a target of 0.5, ...  And then you would like to add the mole fractions as features? (i.e. append that information to the MPNN embedding)? Then you would have a data csv file like:
```
smiles1,smiles2,target
CO, CCO, 0.8
CO, CCO, 0.5
...
```

and a features csv file as
```
fraction1,fraction2
0.3,0.7
0.5,0.5
...
```

Since your system is binary, you could also just use a single number in the features file.

That being said, I think you would better represent your data if you used to mole fractions to weight the MPNN vectors. Unfortunately, this option isn't available in Chemprop yet, so you would need to code it yourself. This option will become available in future releases, but isn't ready yet.

**Comment by hb563** [comment]
Hello @hesther , 

Thank you for your reply. Yes, that is what I am asking.
Would the order of columns (not rows) affect the results?

Also, could you please elaborate on using the mole fractions as weights to the MPNN vectors?

**Comment by cjmcgill** [comment]
Hi @hb563 , the orders of the columns would not affect the results as long as the order was always the consistently same among your different datapoints (rows). That is to say, the first column would always be fraction of methanol and the second would always be ethanol or something like that.

**Comment by cjmcgill** [comment]
@hb563 , when training a model with two molecules, you are training two different mpns. One for the first molecule and one for the second molecule. You are correct that you would have different results and different training for different orderings of the columns under default settings.

I could see you wanting to approach this in two different ways. 1) The first way is if there is some kind of systematic logic to your pairs such that you'd be okay with the two mpns learning different things. Like if you always had an alcohol mixed with an amine or a polar mixed with nonpolar or something. Then you could systematically order them in a reasonable way. 2) If you don't have very clear systematic pairings like that, then I would recommend you train with the option `--mpn_shared`. If you do that, then the two mpns are forced to be the same and you no long have any effect from the ordering of your columns.

**Comment by hesther** [comment]
@cjmcgill already answered the question regarding order. I would also recommend ordering your data or using a shared MPNN. Even with a shared MPNN there will be some dependence on order since your feature input also depends on the order of the molecules.

If you want to use mole fractions for weights, you could customise [Line 264 in mpn.py](https://github.com/chemprop/chemprop/blob/3f20ca46d5b380503eea28734e778cb5db9f309a/chemprop/models/mpn.py#L264), e.g. instead of appending your mole fractions to the MPNN output, you could instead multiply the respective sections. However, since neural networks are universal function approximators, you can also keep the current behavior (of concatenating), and make your FFN sufficiently large so it can learn that relation.

**Comment by hb563** [comment]
@cjmcgill @hesther Thank you both for the clarifications and suggestions. I'll try implementing the changes to mpn.py.

Just to confirm, by using the `--mpn_shared` option, even if I were to add the rdkit features (200/molecule) manually, as long as the rows correspond, 
then this:
|  smile_1  |  smile_2  |  smile_1_ft1  |  smile_1_ft2  | ... |   smile_1_ft200  |  smile_2_ft1  |  smile_2_ft2  | ... |   smile_2_ft200  |
| -------------------------------------------------------------------------------------------------------------------------------- |
|  molec1  |  molec2  |   molec1       |      molec1    | ... |    molec1           |   molec2       |  molec2        | ... |  molec2              |

should be the same as this?
|  smile_1  |  smile_2  |  smile_2_ft1  |  smile_2_ft2  | ... |   smile_2_ft200  |  smile_1_ft1  |  smile_1_ft2  | ... |   smile_1_ft200  |
| -------------------------------------------------------------------------------------------------------------------------------- |
|  molec1  |  molec2  |   molec2       |      molec2    | ... |    molec2           |   molec1       |  molec1        | ... |  molec1              |

**Comment by hb563** [comment]
@hesther Thank you for for your response and further clarification on the matter. I'll train the model differently and see if it would be worth implementing the change. The additional features are temperatures for each mixture, or the one of the additional features (rdkit, morgan etc). 

As for using the mole fractions for weights, when you said multiply the respective sections in [line 264 of mpn.py](https://github.com/chemprop/chemprop/blob/3f20ca46d5b380503eea28734e778cb5db9f309a/chemprop/models/mpn.py#L264), did you mean the output of the concatenated tensors?

**Comment by hesther** [comment]
Yeah, I would multiply and then add them up element wise, cutting the length in half, because that would make it permutation invariant

**Comment by cjmcgill** [comment]
@hb563 , late to respond again but wanted to follow up for the correction. @hesther is right that even with --shared_mpn you would still have order effects because of the treatment of the features elements in the ffn.
