### ISSUE TITLE
Training with mpn_shared

### ISSUE THREAD

**Issue by al967** [chemprop/chemprop#202]
I am training a two component system with two targets and thought to use the mpn_shared argument. However, with everything being the same and only including mpn_shared, it produced worse results.
 More specifically, without the argument, the model's performance for both targets was comparable (i.e. +/- 0.05); and with the argument, the difference increased to +/- 1.5.

Why would this happen given that the function of this argument is to use same MPN for all molecules?

**Comment by hesther** [comment]
Whether a shared MPN makes sense depends a lot on your data, and whether you would want to extract the same features out of both. E.g. if you had a 50%/50% mixtures of different molecules, and were interested in an overall property of the mixture, you should use a shared MPN because both molecules should be encoded the same way (and the order doesn't matter). If instead you have e.g. a database of SN2 reactions and the first molecule is always the electrophile and the second the nucleophile, they have distinct roles and should be encoded separately.

From the performance decrease you report I would assume that each component in the two component system has a distinct role, and different features are extracted in the MPN step for each component.

**Comment by al967** [comment]
@hesther Thanks for the explanation!
