### ISSUE TITLE
antibiotic data format

### ISSUE THREAD

**Issue by sailseem** [chemprop/chemprop#207]
Dear developer,
  Sorry to bother you, i am new to this, but I am wondering, can I train my own data using this? What's the original input for antibiotic data, like one column is smiles, the other is the inhibitory rate (ranging 0.0-1.0?), or just classification based on inbition, like 1 means can inhibit bacteria, well 0 means not work.   Thanks a lot and sorry for such a silly question.

Bests,

**Comment by hesther** [comment]
Hi @sailseem, not a silly question at all!

If you are asking about the data in [the antibiotics paper](https://www.cell.com/cell/fulltext/S0092-8674(20)30102-1), it was binarized, such as:
smiles, inhibition
CCC, 0
CCCC, 0
(these are not molecules actually in that dataset, I just made them up). 

You can train chemprop on any data, regression models on any targets, binary classification models for targets of 0 or 1, as well as multiclass-classification if you have more than 2 classes. It really depends on what you want to achieve with the model. If you train on custom data, make sure to read through the README so you can make good hyperparameter selections, such as aggregation, whether you want additional molecular features, etc. If you tell me a bit about your data, I can also make some recommendations.

**Comment by sailseem** [comment]
Thank you for such a prompt and kind reply, well, I  am trying to explain my dataset.   

1. Basically, I have inhibitory effect data across 1000 compounds, which can be normalized as ranging 0 to 1. In your suggestion, I need to convert the dataset to a binary model like setting a cutoff 0.8, >0.8 equals 1, <0.8 equals 0 to train the model and apply it to a larger compound library, right? This is my first question.     
2.  What if I would like to add another dimension, like the toxicity, to make a model to choose the best inhibitory effect but with less toxicity. This part, let's assume, I don't have the real toxicity yet, can I train a model based on toxic21 library first and apply it to my 1000 compound library to generate the toxic column, can I do it this way, Or, I have to conduct a real toxic assay but with the same concentration used for the inhibitory assay.  That's my second question.
3. And my third question, if I have these two columns of data, how can I train them together, or do I have to train one by one to make a model better inhibitory effect but low toxicity.
4. Well, the last is getting confused. I am trying to explain it. What if I still have other columns like the gene expressions, which could be another 10 or 20 columns, each column represents one single gene expression. I can set a cutoff as a higher expression or lower expression to make it binary as well. Ideally, to get a model feels like, some compounds could have an inhibitory role with less toxicity, also can induce some certain gene expressions but inhibit other gene expressions as well. 


I hope I explained this well and truly sorry for any inconvenience I caused, thanks again for your valuable time.
Bests,
Fan

**Comment by hesther** [comment]
With the warning that I am a chemist and programmer, not a biologist or into medicine, I think I would suggest the following:

1. You can either train a binary model (and binarize your data just as you wrote), or train a regression model to predict the full range between 0 and 1 (and then only take predictions that are above a certain threshold). In my experience, this will not make a huge difference, you can choose whatever you prefer. In the halicin antibiotics manuscript, they trained a binary model. That being said, a model trained on 1000 compounds will not be very general. Deep learning frameworks such as d-d-MPNNs (such as Chemprop) usually perform very well if you have between 10k and 1M datapoints. But as shown in the manuscript, you can still be lucky with a model trained on much less data. Is it is worth a try, but you should keep that in the back of your mind. Once you have a model, you can apply it to a large library and keep the highest scoring molecules. The downside of this approach is that you can only find molecules that are already in a library, not new ones. Finding new molecules is a different type of machine learning, though (generative models), and can be quite complicated. So training a model and applying it to a library is probably a reasonable choice.

2.+3 If you have experimental data for the same molecules as for the inhibition model, that would probably be best. If you do not have it, you can probably also use other data such as tox21, but your model might be less accurate for the molecules you are interested in. You can either train a separate model for toxicity, or a multitask model for inhibition and toxicity. Since inhibition and toxicity are based on different mechanisms and may focus on different parts of the molecules, I think it would be best if you had two separate models (one for inhibition, one for toxicity, regardless of where the data comes from). So you would not create an additional toxicity column, but have that data and model completely separate. You can then combine the scores as you like (e.g. if your model has 0.8 for inhibition and 0.2 for toxicity, it is probably better than something with 0.9 inhibition and 0.9 toxicity). You can then combine these scores heuristically, eg. score(inhibition)-score(toxicity) and look for the best molecules.

4. If your gene expression data is related to each other, you could train one multi-task model for the 10-20 columns. If the data is unrelated (i.e. the value of gene expression 1 has absolutely nothing to do with gene expression 2, and results from very different parts of the molecule), you could also train multiple single models. I do not know how accurate the models in either case would be, since my knowledge on gene expression is rather basic. If you have these models, you can combine the scores, such as f1*score(inhibition)-f2*score(toxicity)+f3*sum score(wanted gene expressions)-f4*sum score(unwanted gene expressions). You would need to figure out how important the different objectives are, for example is it more important you don't have unwanted gene expression induction (high f4), or are gene expression induction/inhibition much less important than inhibition and toxicity (f1 and f2), ... You could then use these criteria to filter through a database and propose molecules that fit all criteria. However, such optimisations (multi-objective optimisations) are really tricky to achieve, so don't be disappointed if your performance is not that great. There are also more complicated ways of combining the scores you might want to try. Also, the performance of each of the models needs to be rather good for these tasks, so the more data you can gather, the better.

I wish you all the best with your model. In the best case, your model will be as good as the data you put in, so carefully think about which data you want to use for each model (and whether they have similar structures to molecules you are interested in).

**Comment by sailseem** [comment]
Thanks a lot, what can I say. For me, such a new programmer in biology, your reply encourage me a lot. It is a difficult progress in learning all of this new staff without any guidance. I feel so warmful and insightful about your detailed answer, I will look into it. And realllllllly appreciated your kindly help! Thanks, again!

**Comment by cjmcgill** [comment]
Hi @sailseem , wanted to follow up and see if this is going well for you and if your question has been resolved?
