### ISSUE TITLE
Argument dictionary for sklearn

### ISSUE THREAD

**Issue by hesther** [chemprop/chemprop#211]
While working on the imputation, I noticed that the terminal output for sklearn models is pretty screwed up, with very long dictionaries specifying the strings of all argument options. It seems to have been like this every since (checked out a few commits that were older than a year). Maybe someone else could confirm this?

Try running e.g. 
```
python sklearn_train.py --data_path tests/data/classification.csv --dataset_type classification --model_type random_forest --single_task
```

and look at the terminal output.

**Comment by cjmcgill** [comment]
I'm also observing this.

Also, I'm getting this message when I run your example job:

> Warning: Found a task with targets all 0s or all 1s
100%|███████████████████████████████████████████| 12/12 [00:06<00:00,  1.75it/s]
Test auc = 0.7003623472812855
1-fold cross validation
	Seed 0 ==> test auc = 0.700362
Overall test auc = 0.700362 +/- 0.000000
/home/charles/Darpa_AMD/AMD-ML/chemprop/chemprop/train/cross_validate.py:167: RuntimeWarning: Mean of empty slice
  mean, std = np.nanmean(task_scores), np.nanstd(task_scores)
/home/charles/anaconda2/envs/chemprop/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1664: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

This is weird since all tasks in that file have a mix of classes. Default behavior (running current master branch) is to do single task calculations for each task when there are any missing tasks, so I wonder if it's incorrectly removing datapoints. Like maybe it's removing data from all tasks if it's missing any task.

**Comment by hesther** [comment]
Yeah, unfortunately the current code doesn't revert (never did) automatically, and if you had missing values it would not even raise a proper ValueError (which I fixed in the current PR at least for obviously missing values). However, if a split is all 0s or 1s, these edge cases are not captured (never were).

**Comment by hesther** [comment]
Oh wait, the split being all 0s or 1s will also be a problem with single task, so no value in reverting anyways.

**Comment by cjmcgill** [comment]
The meaningful error is very nice!

**Comment by cjmcgill** [comment]
I think I see where this issue is coming from. The big text dump is coming from `debug(pformat(vars(args)))` in `run_sklearn`. The pformat thing was part of a long ago release for main chemprop and I guess was not removed from here when everything else was updated. This can be removed entirely because it's redundant with the `debug(args)` in `cross_validate`. Also we can get rid of the pformat import.
