### ISSUE TITLE
features_path not working when features contain missing values

### ISSUE THREAD

**Issue by solita-vilmaja** [chemprop/chemprop#221]
I am generating features with `chemprop.features.features_generators.get_features_generator(features_generator_name='rdkit_2d_normalized')`, writing them to csv-file and providing `features_path`-argument for `chemprop_train`. Features contain some missing values and I am getting the following error

```
Traceback (most recent call last):
  File "bin/chemprop_predict", line 8, in <module>
    sys.exit(chemprop_predict())
  File "lib/python3.6/site-packages/chemprop/train/make_predictions.py", line 176, in chemprop_predict
    make_predictions(args=PredictArgs().parse_args())
  File "lib/python3.6/site-packages/chemprop/utils.py", line 437, in wrap
    result = func(*args, **kwargs)
  File "lib/python3.6/site-packages/chemprop/train/make_predictions.py", line 53, in make_predictions
    skip_invalid_smiles=False, args=args, store_row=not args.drop_extra_columns)
  File "lib/python3.6/site-packages/chemprop/data/utils.py", line 213, in get_data
    features_data.append(load_features(feat_path))  # each is num_data x num_features
  File "lib/python3.6/site-packages/chemprop/features/utils.py", line 50, in load_features
    features = np.array([[float(value) for value in row] for row in reader])
  File "lib/python3.6/site-packages/chemprop/features/utils.py", line 50, in <listcomp>
    features = np.array([[float(value) for value in row] for row in reader])
  File "lib/python3.6/site-packages/chemprop/features/utils.py", line 50, in <listcomp>
    features = np.array([[float(value) for value in row] for row in reader])
ValueError: could not convert string to float: 
```
If I use call `chemprop_train` with `--features_generator rdkit_2d_normalized` for the same data, I don't get any errors. How you handle missing values internally?

**Comment by hesther** [comment]
Dear @solita-vilmaja, how do you get missing values? Generally, we don't support missing feature values, and it is the user's responsibility to input correct features. Since it works with `--features_generator rdkit_2d_normalized`, I assume there aren't any missing values in that case. How did you create the features? An easy way would be to run 
```
python scripts/save_features.py --data_path <your data path> --save_path <where to save features to>
```
which will create a npz file. What features are missing? Single values or full rows (a full row could arise from an invalid smiles)?

**Comment by solita-vilmaja** [comment]
Dear @hesther, thank you for quick reply. I generate features in following way
```
from chemprop.features.features_generators import get_features_generator
import numpy as np

generator = get_features_generator(features_generator_name='rdkit_2d_normalized')
features = []
for smiles in smiles_list:
    features.append(generator(mol=smiles))
np.savetxt("features.csv", np.asarray(features), delimiter=",")
```
The above approach works in some cases, however for example, this smiles generates missing value at least in one position: `S=[W]=S`. With this smiles in dataset, I can still successfully run  `chemprop_train` with `--features_generator rdkit_2d_normalized `.

**Comment by hesther** [comment]
Oh, I see. Your CSV file is missing a header. If you add a header, it works. The CSV file must be of form:
```
feature1, feature2, feature3, ...
0.0, 0.5, 0.2, ...
0.9, 0.2, 0.3, ...
```
(the header can be anything you like, but must have the correct number of columns)

**Comment by solita-vilmaja** [comment]
My bad, in my example I don't have a header but adding it does not solve the problem with missing values.

**Comment by hesther** [comment]
Hi @solita-vilmaja, are you sure? Because I ran your example smiles string `S=[W]=S` with and without a header with the code you provided, and it worked fine with the header, but produced the error you reported without the header. 

Anyways, I just looked through the code because I was confused that NaN values were accepted, and we actually set them to zero (sorry I didn't remember that in the first place). So you can actually read in features files with NaN values, and that is what happens if you use the `--features_generator` flag for `S=[W]=S`, or read in the correctly formatted file.

**Comment by cjmcgill** [comment]
Hi @solita-vilmaja , wanted to follwo up. Is this still giving you trouble?

**Comment by cjmcgill** [comment]
Hi @solita-vilmaja following up. We don't have plans to add capability to run with missing features as provided by `--features_path`. That would be addressed by figuring out some value to best approximate the missing one (nearest neighbor for which it's populated for example), and for now we would leave that to the people providing the data to determine how best to fill in missing values. But please re-open if there's something else you'd like to discuss.
