### ISSUE TITLE
Loading a pretrained model without freezing, but changing the FFN layers

### ISSUE THREAD

**Issue by chstem** [chemprop/chemprop#224]
I would like to evaluate how a model trained on a larger dataset with multiple target properties might improve training on a small dataset for a different target property.

For this I ran the first training ("pretraining"), and then loaded this pretrained model with `--checkpoint_frzn`, so the MPN encoder is reused and only the FFN is optimized on the new target property of the smaller dataset. This also allows me to change hyperparameters like `--ffn_hidden_size`. Everything fine so far.

But I also want to compare how the pretrained model will effect the final model if the MPN weight are not frozen, but only used as an initial guess. So I loaded the model with `--checkpoint_path`, but this time I cannot change any hyperparameters, because the `load_checkpoint()` function does not take the parameter `current_args` as `load_frzn_model()` does.
Additionally, after chemprop loads the whole pretrained model, torch throws warnings because the final layer does not match the number of target columns in the dataset.

```
UserWarning: Using a target size (torch.Size([50, 1])) that is different to the input size (torch.Size([50, 18])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
```

The model will still train, but the unused 17 values in the final dimension are messing things up a bit. The rmse in `test_scores.csv` did not match the reported test rmse of the CLI output anymore. I did not look for further problems.

What I actually expected was, that chemprop would only load the MPN layers, as the FFN layers do not match the new training arguments.

This lead me to a couple of questions:
1. How can I load the MPN weights as an initial guess (without freezing) for a model with different FFN hyperparameters?
1. Why are `load_checkpoint()` and `load_frzn_model()` implemented so differently? 
1. Wouldn't it be easier to just have `load_checkpoint()` and then some command line option `--freeze_mpn` and `--freeze_ffn`?

I did a little bit of digging and found that `load_checkpoint()` actually did have a parameter `current_args` once. But for some reason this was removed.

**Comment by cjmcgill** [comment]
Hi @chstem. The frozen_layers and load_checkpoint operations were considered at very different times and with different goals in mind, so they did get implemented pretty differently.

The load_checkpoint function was made primarily as a way to load a model for either prediction or restarting from a prematurely ended training. It is expecting to have the same arguments and same targets as the initial model. The transfer learning applications are secondary and envisioned having the the same targets between initial and secondary training. It is carrying forward all the weights from previous as the initializations with the same targets, so it has to have the exact same model structure in both the MPNN and FFNN to match those old values with the right new value locations. They can't have more/less values, in different locations, or with different connecting activation functions or else they won't function well as initializations.

The frozen_layer implementation is imagining a different scenario. It's not imagining having the same or even necessarily very similar outputs. It will not supply initializations for the non-frozen layers, those are fully random initialization. The nonfrozen layers have no link to the loaded checkpoint model and can be any shape you want and so have full flexibility with structure parameters. Things like adding new molecular features or having totally different numbers of ffn_layers are expected.

So to answer your question:

1. There is not a way to do this in the current code as it was not an expected use-case. However we do have a couple of options on a developer-user level to allow you to do this. I think the easiest way would be to go to chemprop/models/model.py and comment out/remove the `if args.checkpoint_frzn is not None:` block within the create_encoder function and then run as if you were freezing those layers but they will still train.

2. The difference is largely due to the flexibility that is present in the FFNN in the frozen checkpoint loading. It's an implementation that allows for some variable amount of the model to be kept as random initialization. And allows (perhaps unnecessarily) for both to be used simultaneously.

3. It's very possible there is a more compact way to do both of these functions in one place with some argument logic. Or with a more cleanly parallel structure at the very least.

With more feedback that people want more flexibility in these functions, restructuring them is certainly something that we would want to look into. We expect that either a fully trainable model or a model with frozen layers will usually be the superior to a partially initialized structure. So if you find otherwise for your application case, please do let us know and that will be a strong incentive to rework these functions.

**Comment by chstem** [comment]
Thank you for the quick response. I will definitely test it.

However, I suspect success might strongly depend on the situation. It would be much easier for everyone to test this for themselves if the command line parameters would support this.

**Comment by cjmcgill** [comment]
Hi @chstem how did this workaround function for you?

**Comment by chstem** [comment]
Hi @cjmcgill ,
the workaround works fine, thank you. But the results are, as expected, mixed.

Feel free to close the issue, unless you plan to implement a CLI switch.
