### ISSUE TITLE
Request: Better fingerprinting support for multi-molecule models

### ISSUE THREAD

**Issue by colinrsmall** [chemprop/chemprop#236]
I may be able to tackle this at some point this year, but I figured I'd still write this down in case someone can get to it sooner.

I have two main requests for fingerprinting with multi-molecule models:

1. For models with a shared MPN network, it would be nice to allow a mismatch between the number of molecules the model is trained on and the number of molecules passed in for fingerprinting for a fingerprint type of "MPN". Specifically, it would be convenient to allow a list of singular molecules as input for fingerprinting, since you currently need to be a little crafty with how you build the fingerprinting input data for multi-molecule models.
2. Fingerprinting column naming could be molecule-number aware. Currently it just assigns column names in sequential order. E.g. For a two-molecule network with a fingerprint size of 2, the fingerprint column names are currently ["fp_1", "fp_2", "fp_3", "fp_4"] but could be ["fp_1_mol_1", "fp_2_mol_1", "fp_1_mol_2", "fp_2_mol_2"] or something similar.

**Comment by cjmcgill** [comment]
These are good suggestions. The shared_mpn support especially is something we want to fix. We welcome the engagement if you want to propose code and would support that. Otherwise this is something we should be able to push a fix for before too long. If you have any other notes for the fingerprint function please let us know and we can wrap them into the PR as well.
