### ISSUE TITLE
interfacing chemprop with hgraph2graph

### ISSUE THREAD

**Issue by amir-tagh** [chemprop/chemprop#298]
Hello,

my question is not directly related to chemprop but I thought you might be able to help with my issue with interfacing chemprop with hgraph2graph.

by using the following command I have created the checkpoints required by hgraph, I got the (args.json, fold_0, verbose.log, test_scores.csv, quiet.log) but I can not figure out which one needed to be used for hgraph and unfortunately there is no explanation on the hgraph github.

Thanks inforward,
Amir

chemprop_train --data_path Inforna_logP_main.csv --dataset_type regression --split_type scaffold_balanced --save_dir Inforna_logP_checkpoints

**Comment by kevingreenman** [comment]
It seems that you're asking about the [finetune_generator](https://github.com/wengong-jin/hgraph2graph/blob/master/finetune_generator.py) script in hgraph2graph, e.g. using a command like

```
python finetune_generator.py --train ${ACTIVE_MOLECULES} --vocab data/chembl/vocab.txt --generative_model ckpt/chembl-pretrained/model.ckpt --chemprop_model ${YOUR_PROPERTY_PREDICTOR} --min_similarity 0.1 --max_similarity 0.5 --nsample 10000 --epoch 10 --threshold 0.5 --save_dir ckpt/finetune
```

I believe you're asking about what you should use for `${YOUR_PROPERTY_PREDICTOR}`. 

I'm not a regular user of hgraph2graph, but my understanding from the [Chemprop constructor in the hgraph2graph code](https://github.com/wengong-jin/hgraph2graph/blob/e396dbaf43f9d4ac2ee2568a4d5f93ad9e78b767/finetune_generator.py#L33) is that you should use the `fold_0` directory, because the constructor will walk this directory to find the model checkpoint files (`.pt`), similarly to how chemprop loads models from checkpoint directories.

**Comment by amir-tagh** [comment]
Hi Kevin, Thanks for your help. I am directing the  --chemprop_model to where I have the checkpoint file (model.pt),
but I am getting the following error,
again not related to chemprop but wondering if you can point me on how solve this.


File "/apps/hgraph2graph/20210428/hgraph2graph/finetune_generator.py", line 37, in __init__
    scaler, features_scaler = load_scalers(fname)
ValueError: too many values to unpack (expected 2)

**Comment by amir-tagh** [comment]
Thanks for your help, it solved my problem.
I am sorry for dumping unrelated questions here, I am not getting any feedback from hgraph.

now I am getting an error after training starts in finetune_generator code. It seems that it is connected with moving data between CUDA and CPU but I can not find out how to fix it.

Thanks again for your help.

Moving model to cuda
Loading from checkpoint ckpt/inforna-pretrained/model.ckpt.5000
After pruning 257 -> 257
Epoch 0 training...
  0%|          | 0/13 [00:25<?, ?it/s]
Traceback (most recent call last):
  File "/apps/hgraph2graph/20210428/hgraph2graph/finetune_generator.py", line 152, in <module>
    meters = meters + np.array([kl_div, loss.item(), wacc * 100, iacc * 100, tacc * 100, sacc * 100])
  File "/apps/hgraph2graph/20210428/lib/python3.7/site-packages/torch/_tensor.py", line 732, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by cjmcgill** [comment]
We're definitely getting outside the scope of Chemprop, so I am going to close this issue, but will keep chatting in case I can help.

Hard to say exactly where the GPU issue is without deep investigation. But I would try converting the tensor to numpy using `tensor.detach().numpy()` instead of `np.array(tensor)`.
