### ISSUE TITLE
memory leakage when inference

### ISSUE THREAD

**Issue by HanSangJun** [chemprop/chemprop#32]
Hi,

I found memory leakage (not GPU memory, but RAM) when inference.

As the number of inference increases, the amount of allocated memory also increase.

Thanks.

**Comment by swansonk14** [comment]
Hi @HanSangJun,

Thank you for the question! There should be some degree of RAM usage increase during inference since we are creating a list that holds the results across all batches of the test set on which inference is being performed. However, the memory usage should not be very large. What sort of RAM usage numbers are you seeing? Also just to clarify, is this during inference on the validation or test set in `train.py` or is this when running `predict.py`?

Thanks,
Kyle

**Comment by HanSangJun** [comment]
I modified your code to combined with my algorithms, and I found caching mechanism 
`if cache: SMILES_TO_GRAPH[d.smiles] = mol_graph`
filled my RAM.

I disallowed that mechanism. Thank you.

**Comment by swansonk14** [comment]
Okay great, I'm glad you found that!
