### ISSUE TITLE
ZINC15 Dataset

### ISSUE THREAD

**Issue by Miserlou** [chemprop/chemprop#33]
Hey guys!

Sorry to bother again, but do you happen to have a pre-processed version of the (complete) ZINC15 dataset you use in your Cell paper? Or, alternately, can you release the scripts which you used to prepare it? I can't find it in your released data archive.

Cheers!
Rich

**Comment by swansonk14** [comment]
Hi Rich,

Thanks for the question! We didn't add the ZINC15 data to the chemprop repo since it's a huge dataset, but it's pretty easy to download the SMILES directly from the [ZINC15 website](https://zinc15.docking.org/). To download them, go to the [tranches](https://zinc15.docking.org/tranches/home/#) page and then select the tranches you want (we have a list in the Cell paper) and click the download button. It will first download a list of URLs, and then you can use those URLs to download `.smi` files with the raw SMILES. We didn't do any pre-processing after that, we just directly used those SMILES.

I hope this helps and please let us know if you have any other questions!

Best,
Kyle
