### ISSUE TITLE
[QUESTION]: Why are most of the uncertainty methods by Hirschfeld et al. not implemented in the current framework? 

### ISSUE THREAD

**Issue by msk235** [chemprop/chemprop#349]
Hi all,

I am curious why most of the uncertainty methods (Union Based and Distance Based Methods) evaluated by Hirschfeld et al. in 2020 are not implemented in the current Chemprop Framework. Is there a particular reason for this? 

Thanks for your help!

**Comment by davidegraff** [comment]
No particular reason- MVE was the most robust method based on all evaluation metrics, so that was prioritized. In any case, all of those uncertainty metrics have some type of flaw and none of them are truly trustworthy, so there's little justification to spend the effort implementing more of them.

**Comment by cjmcgill** [comment]
The external appearance of the chemprop uncertainty methods are similar to the Hirschfeld fork, but the way they are implemented is completely different. Adding new types of method (like Union or distance) would be writing in totally new structures into chemprop rather than merging from another fork. 

Though we're not providing support for distance and union, the fingerprint function should be able to give you the information you'd need to make those calculations externally.

**Comment by msk235** [comment]
@davidegraff thanks for your quick reply! I understand there is not much additional merit in the other evaluation methods then. 

@cjmcgill thank you for explaining the difficulty in implementing the other methods mentioned in the paper. Given @davidegraff s reply, I can see why you decided against it.
