### ISSUE TITLE
[QUESTION]: ENCE evaluator after calibration with "tscaling" method 

### ISSUE THREAD

**Issue by msk235** [chemprop/chemprop#365]
Hi all, 

I have a question regarding the ENCE evaluator when using the "tscaling" calibration method (file: uncertainty_evaluator.py, line:347 - 351). I don't understand completely why the conversion back to sample stdev is needed.

Why is it not possible to use the standard deviation directly for evaluation, as is the case with the other calibration methods?  The standard deviation is ultimately also the uncertainty measure output in the prediction file.

With the code as it is at the moment I receive higher ENCE after calibration with the "tscaling" method than before applying it. This appears inconsistent to me. However, I receive lower values for the miscalibration area evaluator after calibrating with the "tscaling" method. 

Thanks for your help!

**Comment by davidegraff** [comment]
@cjmcgill should be able to answer this question

**Comment by JacksonBurns** [comment]
After some changes since this issue was opened, I believe this issue is referencing the lines starting here: https://github.com/chemprop/chemprop/blob/master/chemprop/uncertainty/uncertainty_evaluator.py#L362

**Comment by cjmcgill** [comment]
Hi @msk235, the t-scaling method has an extra step in the treatment compared to z-scaling.

Z-scaling assumes that all predictions are sampled from a normal distribution around the true target values. It applies a scaler value to the standard deviation of an uncertainty prediction that optimizes the log-likelihood of the predictions against the target on a normal distribution.

T-scaling handles this slightly differently. First, the distribution that it applies log-likelihood from is the t-distribution instead of the normal distribution. Second, it assumes that the error is due primarily to random variation between ensemble members, so it divides the error by the square root of the number of ensemble models. Reducing the predicted uncertainty in the mean because it's drawing from a distribution that has been sampled many times. As it happens, most errors are not purely a result of sampling repeatedly from a distribution, so this assumption is usually not appropriate. Z-scaling is almost always the better choice.

Calculating ENCE requires knowing the initial variance predicted by the uncertainty for calculation. The reduction due to the number of ensemble members and the distortion from using the t-distribution aren't helpful there. So the original sample variance is recalculated for calculating ENCE.
