### ISSUE TITLE
[QUESTION]: On my PC after trying --split_type scaffold_balanced this error is produced targets = np.array([d.targets for d in data_set], dtype=np.float)    raise AttributeError("module {!r} has no attribute " AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?

### ISSUE THREAD

**Issue by Rah-T** [chemprop/chemprop#379]
**What are you trying to do?**
Please tell us what you're trying to do with Chemprop, providing as much detail as possible

**Previous attempts**
If possible, provide some examples of what you've already tried and what the output was.

**Screenshots**

**Comment by shihchengli** [comment]
I think that is due to the NumPy version you used. NumPy 1.24 [(release notes)](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) removed aliases of `np.float`, causing an error when it is used. If you installed Chemprop from source, you can simply update your code by running `git pull`. The issue has been solved at #357. If you still want to use the old version of Chemprop, you can downgrade your NumPy version to 1.20. Closing this issue now, feel free to reopen if you have more questions related to this.
