### ISSUE TITLE
[BUG]: MCC loss function for binary classification returns predicted values of 'NaN'

### ISSUE THREAD

**Issue by YoochanMyung** [chemprop/chemprop#380]
**Describe the bug**
The MCC loss of binary classification has an issue of returning 'NaN' similar with #306 and #309.
It happens when the denominator of MCC equation gets '0', and this raises `ValueError: Input contains NaN.`

**Expected behavior**
The MCC loss should not be 'Nan'.
Just in case of getting 0 for the denominator,  adding some smoothing factor such as `+1 or 1e-7 (epsilon)` can prevent this error.

Not sure what will be the best case scenario, I referred to the MCC loss of [here](https://github.com/kbressem/faimed3d/blob/main/faimed3d/models/losses.py#L139) and implemented into `loss_functions.py` as below, and it works fine.

```
    numerator = (TP * TN - FP * FN) + 1
    denominator = torch.sqrt((TP + FP) * (TP + FN) * (TN + FP) * (TN + FN) + 1e-7) +1

    mcc = torch.div(numerator.sum(),denominator.sum())
    return 1-mcc
```

**Environment**
- python version: 3.10.6
- package versions:  pytorch=1.12.1
- OS: Ubuntu 22.04.2 LTS

**Comment by cjmcgill** [comment]
Yes, if you have a batch that contains no positive values or no negative values, then you'll get a Nan. This is because the MCC isn't meaningful in a dataset that is only positive or negative. Something that randomly comes up in random batches but rarely in whole datasets.

To avoid this problem with MCC, use the `--class_balance` flag. This will force the same proportion of positives and negatives to be in every batch. You may need to use larger batches to get stable behaviro

Implementing a smoothed version of the MCC loss function is an interesting option. I don't know if it remains as numerically meaningful as normal MCC. Is that repo that implements a smoothing factor associated with a paper that discusses it?

**Comment by kevingreenman** [comment]
We are closing all enhancement requests for chemprop v1.x, as we will not have time to implement these before the upcoming release of [chemprop v2.0](https://github.com/chemprop/chemprop/issues/517). If there is still interest in this enhancement, please open a new issue after the release of v2.0.
