### ISSUE TITLE
[QUESTION]: Pretrained models for SMILES embedding

### ISSUE THREAD

**Issue by parthnatekar** [chemprop/chemprop#384]
Hi,

I was wondering if you have provided access to pretrained models for extracting embeddings from SMILES representations?

Thanks!

**Comment by kevingreenman** [comment]
Hi, thanks for your question. We haven't provided any pretrained models for extracting embeddings from SMILES. Since the embeddings are dependent on the prediction task, it's often best to use embeddings that are tailored to your specific property of interest, or at least to a closely-related property. For example, an embedding pretrained to predict logP would probably not transfer well to predict maximum absorption wavelength, but an embedding pretrained to predict maximum absorption wavelength would transfer better to predict maximum emission wavelength (since both are optical properties). We've made pretraining and transfer learning functionality available in Chemprop so you can try these things out to see what works best.
