### ISSUE TITLE
[QUESTION]: Transfer learning, additional features, and list of checkpoint paths

### ISSUE THREAD

**Issue by nedaojaghlou** [chemprop/chemprop#386]
Hi, can you please explain to me how transfer learning works in Chemprop, and how knowledge transfers? Is it using the same MPNN in the new training or the old one?
Also, can I use the ensemble model as a pre-train model for transfer learning?

Thanks,

**Comment by kspieks** [comment]
Thanks for the question. Broadly, the goal of transfer learning is to pre-train the model on dataset 1 and then continue training on dataset 2. Typically, the two datasets have somewhat related tasks. The knowledge transfers in the sense that the weights from training on dataset 1 are used as the initial guess when training on dataset 2. These weights contain the "knowledge" from dataset 1. The same MPNN architecture would be used during transfer learning. You can load the previous weights using the `--checkpoint_path` argument. Yes you could pre-train n models on dataset 1 and then continue training those ensemble of n models on dataset 2. In this case, the `--checkpoint_paths` argument would be useful.

**Comment by kevingreenman** [comment]
Hi Neda, good to hear from you! 

Adding on to what @kspieks said, Chemprop also has the ability to freeze some parameters when you load a pretrained model, so that when you load the checkpoint to finetune the model on another dataset, only some of the parameters will be allowed to vary. If you only use the `--checkpoint_path` or `--checkpoint_paths` argument as @kspieks said, all of the parameters will be allowed to update when you train on new data.

Copying the relevant [section of the README](https://github.com/chemprop/chemprop#pretraining) here for convenience:

Certain portions of the model can be loaded from a previous model and frozen so that they will not be trainable, using the various frozen layer parameters. A path to a checkpoint file for frozen parameters is provided with the argument `--checkpoint_frzn <path>`. If this path is provided, the parameters in the MPNN portion of the model will be specified from the path and frozen. Layers in the FFNN portion of the model can also be applied and frozen in addition to freezing the MPNN using `--frzn_ffn_layers <number-of-layers>`. Model architecture of the new model should match the old model in any layers that are being frozen, but non-frozen layers can be different without affecting the frozen layers (e.g., MPNN alone is frozen and new model has a larger number of FFNN layers). Parameters provided with `--checkpoint_frzn` will overwrite initialization parameters from `--checkpoint_path` (or similar) that are frozen in the new model. At present, only one checkpoint can be provided for the `--checkpoint_frzn` and those parameters will be used for any number of submodels if `--ensemble_size` is specified. If multiple molecules (with multiple MPNNs) are being trained in the new model, the default behavior is for both of the new MPNNs to be frozen and drawn from the checkpoint. Only the first MPNN will be frozen and subsequent MPNNs still allowed to train if `--freeze_first_only` is specified.

So your options when loading in a pretrained model for fine-tuning are:
1. allow all parameters to vary (use `--checkpoint_path` or `--checkpoint_paths`)
2. freeze MPNN parameters and allow all FFNN parameters to vary (use `--checkpoint_frzn`)
3. freeze MPNN pararmeters and also freeze some FFNN parameters (use `--checkpoint_frzn` and `--frzn_ffn_layers <number-of-layers>`)

Regarding ensembles, you can load those for finetuning using the `--checkpoint_paths` argument as @kspieks said, but we don't currently support freezing MPNN / FFNN parameters in an ensemble.

In theory, the more closely related the task you're transferring to is to the original training task, the more parameters you'll want to freeze, but this is something we recommend testing empirically. We've observed that transfer learning can be challenging to get working in practice and depends on many factors such as size and coverage of both datasets.

**Comment by nedaojaghlou** [comment]
Thank you so much @kspieks and @kevingreenman for your great explanation. It was very helpful.  About the pre-training model, I am using the --checkpoint_dir where the model checkpoint(s) are saved. So I think that it's similar to checkpoint_path.  I used this command before for transfer learning but now it looks like it's not working. It actually creates the folder for the new model args.json, quiet.log, and fold_0, but it's not generating the test_scores.csv file. and here is the error that I've got: 
    features_batch = torch.from_numpy(np.stack(features_batch)).float().to(self.device)
  File "<__array_function__ internals>", line 180, in stack
TypeError: dispatcher for __array_function__ did not return an iterable

**Comment by kevingreenman** [comment]
Could you provide the full traceback for that error? And do you know when this worked for you (either a specific Chemprop version, or approximately how long ago)?

**Comment by kevingreenman** [comment]
@nedaojaghlou are you by any chance using additional/custom features when you're training? I'm wondering if this issue is related to #314 and not limited to transfer learning

**Comment by amirnikooie** [comment]
Thank you @kevingreenman and @kspieks for your responses. It solved a similar problem I had on my side. I have to say using additional features is a subtle point that needs to be considered in transfer learning and I believe that might have been the main culprit behind errors that @nedaojaghlou was getting, in addition potential problems due to different versions or python environments.
Anyways, now I have a related question in case of using ensemble method. Based on the README, the input of `--checkpoint-paths` should be `<list of paths>` to each of the `.pt` files. I'm using chemprop in a python code and not through command line. So, I'm basically creating a list in `arguments` variable and parse it accordingly. For some reason, I couldn't make this `--checkpoint-paths` work in this fashion and each time, I get the error of not such file or directory while reading the `.pt` files. I'd appreciate your help on this. Below, you can see a mock example where I pass the list of paths in the list of arguments I have and so can let me know what is wrong:

_arguments = [
        '--data_path', './chemprop/data/train.csv',
        '--dataset_type', 'classification',
	'--checkpoint_paths', '[./pre-train/model_0/model.pt, ./pre-train/model_1/model.pt, ./pre-train/model_2/model.pt ]'
	'--save_dir', './chemprop/TL_outputs/',
    '--epochs', '20',
    '--bias',
    '--loss_function', 'binary_cross_entropy',
    '--metric', 'auc',
    '--extra_metrics', 'accuracy',
	]
	args = chemprop.args.TrainArgs().parse_args(arguments)_

So, for that part I pass a string, which is a list of 3 paths pointing to each of those `.pt` files. I use a `string` for `parse_args()` as all input arguments are passed as a string. Do you know what the problem can be? I also tried passing a list of strings where each string is a path, but that didn't work either.
Thank you in advance!

**Comment by kevingreenman** [comment]
Hi @amirnikooie, can you try it like this?

```
arguments = [
'--data_path', './chemprop/data/train.csv',
'--dataset_type', 'classification',
'--checkpoint_paths', './pre-train/model_0/model.pt', './pre-train/model_1/model.pt', './pre-train/model_2/model.pt',
'--save_dir', './chemprop/TL_outputs/',
'--epochs', '20',
'--bias',
'--loss_function', 'binary_cross_entropy',
'--metric', 'auc',
'--extra_metrics', 'accuracy',
]
args = chemprop.args.TrainArgs().parse_args(arguments)
```

**Comment by nedaojaghlou** [comment]
> @nedaojaghlou are you by any chance using additional/custom features when you're training? I'm wondering if this issue is related to #314 and not limited to transfer learning

Thank you for your message. You were correct in pointing out that my issue was caused by using additional features and different Python environments. I have successfully resolved the problem now. By the way, I apologize for my delayed response.

**Comment by kevingreenman** [comment]
@nedaojaghlou no problem, thanks for letting me know. I'm glad it's working now!

**Comment by amirnikooie** [comment]
@kevingreenman , thanks for your reply! The suggested solution worked.
The word *list*, in  `<list of paths>` in the original documentation is a bit confusing to me. I didn't know if it means a list type  in python containing the paths or just series of paths for each model separated by commas as you suggested. It may be good to clarify it there by adding couple of sentences or providing a dummy example.
Anyways, thanks again for your help.
