### ISSUE TITLE
[FEATURE]: QM7b dataset in CSV format as other datasets have been provided

### ISSUE THREAD

**Issue by jamshaidsohail5** [chemprop/chemprop#387]
Hi. I hope this message finds you in the best of health. I was looking for QM7b multi-task dataset in the format like other datasets have been provided in the data.tar.gz file (qm8, qm9). Any sort of help by anyone would be highly appreciated.

**Comment by kevingreenman** [comment]
The molecules in QM7b (from the [quantum-machine.org website](http://quantum-machine.org/datasets/)) are represented as Coulomb matrices, which cannot be mapped directly back to SMILES in a unique way. If you need to use QM7b, I know of a couple examples of loading this dataset into a nice format:

* [DeepChem](https://github.com/deepchem/deepchem/blob/master/deepchem/molnet/load_function/qm7_datasets.py)
* [Therapeutic Data Commons](https://tdcommons.ai/single_pred_tasks/qm/)

Since Chemprop only takes SMILES as input, I suggest looking elsewhere for models designed for the representation used in QM7b.

**Comment by jamshaidsohail5** [comment]
Hi. Thank you so much for the swift response. I am working on the problem of uncertainty quantification for molecular property prediction using multi-task learning. It would be nice if you can recommend some good multi-task datasets which are compatible with Chemprop and they also seem to have correlation in the tasks and are best suitable for multi-task learning. I was able to compile the below ones which have a smiles representation too. 

Clintox
PCBA
MUV 
QM8
QM9
SIDER 
TOX21
Toxcast 

Looking forward to hearing from you. Thanks.

**Comment by jamshaidsohail5** [comment]
Also somehow I am able to obtain the molecular embeddings for different molecules in the qm7b dataset along with their properties, would then it be possible to utilize chemprop for multi-task learning and also quantify the uncertainty ?

**Comment by kevingreenman** [comment]
That looks like a great list of datasets you have so far, covering many of the most common benchmarks. Another one I can think of is [this dataset on UVVis properties](https://www.nature.com/articles/s41597-020-00634-8). 

You would not be able to directly use Chemprop with an embedding as an input. You would have to modify the source code to use the functionality we've implemented for multi-task learning and uncertainty with embedding inputs.
