### ISSUE TITLE
Can we featurize in parallel and save molgraph features to disk?

### ISSUE THREAD

**Issue by jasonzdeng** [chemprop/chemprop#39]
My dataset is quite large and it takes many hours to featurize. I wonder if it can be done in parallel and save the featurized data to disk?

**Comment by swansonk14** [comment]
Hi @jasonzdeng, thanks for the question!

I'm not sure which version of Chemprop you were using, but around April I made some changes to the molgraph featurization that should speed it up. Any time a data set has <= 10,000 molecules, all the molgraphs will be cached in memory, meaning the first epoch will be slow but all subsequent epochs will be fast since Chemprop will simply use the cached molgraph rather than recomputing it. For data sets with > 10,000 molecules, Chemprop now uses PyTorch's `DataLoader` to do parallel computation of the molgraphs, making it nearly as fast as using the cached version.

You can control which of these two loading mechanisms are used by modifying the `--cache_cutoff <num>` flag (the default is 10,000). You can also control the number of parallel workers when the size of the data set exceeds the cache cutoff with the `--num_workers <num>` flag (the default is 8).

Does this solve your problem or would there still be a benefit to pre-computing the molgraphs and saving them to disk?

**Comment by jasonzdeng** [comment]
Thanks for the reply. It is helpful. 
However, it would still benefit greatly if I can pre-compute the molgraphs, especially in parallel jobs, and save them disk. My data size is in the range of tens of millions. I made it to work for me by pulling out some of the code to run featurization and modified the training code to load dataset from disks. It would be nice if there is an official update. Thanks!
-Jason
