### ISSUE TITLE
Can I turn off "split_type" flag in train.py to allow the model traning with all data?

### ISSUE THREAD

**Issue by chf42** [chemprop/chemprop#40]
Hi all,

Recently, I am using the train.py to train a predictive model for my data.
**python train.py --data_path <path> --dataset_type <type> --save_dir <dir>**
I know it takes "--split_type random" & "split_sizes (0.8,0.1,0.1)" & "--num_folds 1" by default. So it seems that it does 8:1:1 split into the total data, and only uses 80% of the data to train the model and save it for future prediction.

My questions are
1) What could I do if I want to use 100% of the data to train the model? For example, can I define split_size ---> (1,0,0) in my train code?   

2) The nested cross-validation by tuning num_folds seems different from traditional n-fold cross-validation. According to the codes, it does train/val/test splits for n times, and then output the average test scores. Am I right? 

Also, I wonder whether it will save 5 models if I set num_folds=5. If that's the case, what happens if I use the saved models (with num_folds=5 setting) for prediction? Do it takes the average predictions from the 5 models? The ensemble =1 in above cases. 

Thank you!

**Comment by swansonk14** [comment]
Hi @chf42, thank you for the questions!

1. Yep, training on all the data is as simple as setting `--split_sizes 1 0 0` (though you may see some warning messages). However, it is worth noting that the validation data is used to perform early stopping in order to avoid overfitting, so I would recommend using at least some validation data. When I don't care about measuring test performance, I usually use `--split_sizes 0.9 0.1 0`.

2. Yes, the default splitting in Chemprop (which is not nested cross-validation), simple randomly splits the data into train/val/test for n times. After each fold, it prints out the performance on that fold, and then after all the folds are complete, it prints out the mean and standard deviation across folds.

Yes, if you use `--num_folds 5` then it will save 5 models. If you subsequently load up that checkpoint directory, those models will be treated as an ensemble.

The difference between `--ensemble_size 5` and `--num_folds 5` is that `--ensemble_size 5` will train 5 models on the *same* train/val/test split and average their predictions before computing performance while `--num_folds 5` will train 5 models on 5 *different* train/val/test splits and will separately predict and evaluate with each model before averaging the evaluations.

**Comment by chf42** [comment]
@swansonk14 Thank you much! The detailed explanations are very helpful.
