### ISSUE TITLE
The role of "num_folds" in hyperparameter_optimization.py

### ISSUE THREAD

**Issue by chf42** [chemprop/chemprop#41]
Hi all,

I am a little bit confused about the "num_folds" parameter in hyperparameter_optimization.py. So I submitted this ticket for better understanding.

For example, the script is:

**python hyperparameter_optimization.py --data_path <data_path> --dataset_type <type> --num_iters <n> --config_save_path <config_path> --num_iters <n_iterations> --num_folds <n_folds>**

I assume if num_folds =1, it will do train/val/test split of 8:1:1 for one time, and evaluate num_iters models with different hyperparameter combinations using the test score against 10% data. And the validation score against anther 10% data is used to control the optimal number of epochs.  

Similarly, if num_folds =5, it will do the splits for 5 times, and select the hyperparameters with the highest average test scores across 5 test sets. 

Also, in general, the num_folds setting here is different from the classical n-fold cross-validation, which splits the whole data into n folds and uses n-1 fold for training and 1 fold for testing.

I wonder if my understandings are correct.  Appreciate for any feedback or ideas. 

Thank you!
Cheng

**Comment by swansonk14** [comment]
Hi @chf42, yes your understanding is correct about the way `num_folds` works. It is not the classical n-fold cross-validation but is instead a random sampling for each of the folds, meaning some molecules can be in the same train or validation or test split across different folds. It is possible to manually do a classical cross-validation by creating those splits and then loading them using the `predetermined` split type. We're hoping to add an option for classical cross-validation soon so that manual work is not required, but the current random sampling approach should still be a good approximation to classical cross-validation.
