### ISSUE TITLE
[QUESTION]: Are fingerprints of Invalid SMILES filled with zeros?

### ISSUE THREAD

**Issue by elisammz** [chemprop/chemprop#440]
**What are you trying to do?**
I am trying to get intermediate fingerprints of a given list of smiles and do PCA analysis as in the [`chemprop_colab_demo`](https://colab.research.google.com/github/chemprop/chemprop/blob/master/colab_demo.ipynb#scrollTo=b9IskYn_qj4y).

**Previous attempts**
The length of the array with the fingerprints is the same length of my list of smiles. However, when I try to do a PCA analysis (as in the chemprop colab demo), I get the error: `ValueError: could not convert string to float: 'Invalid SMILES'`

Does that mean that there was an `Invalid SMILES` in my smiles list but the fingerprint of that invalid smile was somehow saved as zero? Moreover, when I run a prediction for that same list of smiles, no `Invalid SMILES` message is showed, meaning that all smiles are valid and predicted without issue.

I think my issue is related to this the bug in [#350](https://github.com/chemprop/chemprop/issues/350) 

This runs fine:
```
nu_arguments = [
        '--test_path', '/dev/null',
        '--preds_path', '/dev/null',
        '--checkpoint_dir', 'some/dir/path',
        '--fingerprint_type', 'MPN'
    ]

  # nu_fps
  nu_args= chemprop.args.FingerprintArgs().parse_args(nu_arguments)
  nu_fps = chemprop.train.molecule_fingerprint.molecule_fingerprint(args=nu_args, smiles= a_smiles_list)
```
This returns: `Invalid SMILES`

```
pca = PCA(n_components=2)
pca_xy = pca.fit_transform(nu_fps.squeeze())
plt.scatter(pca_xy[:,0], pca_xy[:,1], s=30, c=df['N'], edgecolor='w')
plt.colorbar(label='N')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.show()
```
where df is my dataframe with  'smiles' and 'N' columns

Thank you very much for readin!

**Comment by kevingreenman** [comment]
Hi @elisammz, when you say that no `Invalid SMILES` message shows during prediction, do you just mean that there is no error message? If I understand you correctly, you're encountering the error during the PCA step rather than during the execution of the chemprop code.

Having invalid SMILES in your dataset is not expected to lead to an error message for either prediction or fingerprinting. By default, the `return_invalid_smiles` argument in both `[make_predictions](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/train/make_predictions.py#L351)` and `[molecule_fingerprint](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/train/molecule_fingerprint.py#L18)` is set to `True`. This means that when chemprop encounters an invalid SMILES input, it will return the string "Invalid SMILES" rather than a numerical prediction (or in this case, the fingerprint). The length of the array of fingerprints should always be the same as the length of the list of SMILES, but if you check your array of fingerprints, I think you'll find that some of them are "Invalid SMILES" rather than a fingerprint vector. Similarly, if you inspect the prediction results, I think you will also find "Invalid SMILES" in the output values.

You can use the functions `[get_invalid_smiles_from_file](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/data/utils.py#L289)` or `[get_invalid_smiles_from_list](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/data/utils.py#L311)` in `chemprop/data/utils.py` to help you identify which of your input SMILES are invalid.

**Comment by elisammz** [comment]
Hi @kevingreenman. Thank you again for your amazing suggestions!

> You can use the functions [get_invalid_smiles_from_file](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/data/utils.py#L289) or [get_invalid_smiles_from_list](https://github.com/chemprop/chemprop/blob/f3d1bff19a6e1b03d28e9cfabdf4c80dd8c67382/chemprop/data/utils.py#L311) in chemprop/data/utils.py to help you identify which of your input SMILES are invalid.

I made use of these functions and I checked the array of my fingerprints. No `Invalid SMILES` was found. The error was during the PCA step. Thanks!

**Comment by kevingreenman** [comment]
@elisammz Did you mean to close the issue? From your response, it sounds like your problem isn't resolved yet
