### ISSUE TITLE
[QUESTION]: GNN backend refactor question

### ISSUE THREAD

**Issue by mefortunato** [chemprop/chemprop#477]
Hi, I've been lurking and following along with the v2 refactor and recently saw #457 and #470 which sparked some interest. I didn't think changes to the graph data structure was going to be in scope for the v2 refactor, but after seeing this I am curious if you have considered DGL for [graph representations and message passing](https://docs.dgl.ai/en/0.8.x/guide/message-api.html#guide-message-passing-api) in addition to pytorch geometric. I have played around with both to implement molecular graphs and the chemprop DMPNN architecture, and strongly prefer the DGL APIs, although I appreciate this is a personal preference. DGL also offers [graph data loading](https://docs.dgl.ai/en/0.8.x/generated/dgl.dataloading.GraphDataLoader.html#dgl.dataloading.GraphDataLoader) that takes care of batching, offering potential to eliminate some technical debt here. Lastly using a common data structure with either pytorch geometric or DGL would offer modular compatibility with [other GNN architectures](https://docs.dgl.ai/en/0.8.x/api/python/nn-pytorch.html) and pooling algorithms. Right now it would be cumbersome to use any other encoder with the data structure specific to chemprop, or vice versa.

There is also an [open-source project built on top of DGL](https://github.com/awslabs/dgl-lifesci) that has pretty elegantly built [graph featurization infrastructure](https://github.com/awslabs/dgl-lifesci/blob/master/python/dgllife/utils/featurizers.py) for chemical graphs that could easily be extended to support the requirements of chemprop. There's even an [open issue](https://github.com/awslabs/dgl-lifesci/issues/195) to implement chemprop's DMPNN in their package

As mentioned, I've already implemented a lot of code required to use DGL/dgllife/lightning to train DMPNN models and would be happy to discuss further if you're not already sold on this torch_scatter backend refactor.

**Comment by davidegraff** [comment]
Hi Mike,

Thanks for bringing this up! It's a topic we've discussed internally at length, and the current leaning of the dev team is that there are no plans to either (1) port the Chemprop backend to any of the graph-learning libraries like PyG, DGL, etc.; or (2) submit a Chemprop implementation to any of these libraries. There are a couple of reasons why we decided not to pursue either of these with the v2 rewrite:

- **level of abstraction**: In order to accommodate the zoo of model architectures these libraries provide, their object model is necessarily abstract. We aim to keep the Chemprop library specific to the D-MPNN architecture of the original paper,[^1] allowing the code to more directly follow the theoretical formulation and benefit from faster, more direct code.
- **speed**: By minimizing the need to adhere to high-level, abstract interfaces and datatypes, we can minimize the total number of function calls as well as rely on our own faster implementations. That is, if we implemented Chemprop in DGL, it would make no sense to have our own `MolGraphFeaturizer` class. However, I can tell you by looking at their graph featurization API, it is _noticeably_ slower than the v2 version we've written (because their code is essentially our v1 featurization code and the v2 code is about 60% faster).
- **learning curve**: This is in some sense a weaker argument (but a strong one to the dev team) and it's the dev team is already familiar with the Chemprop object model. As the folks tasked with maintaining and extending the library, it would be a _considerable_ lift for us to uproot our entire understanding of the library and move it to a new framework _just because_. It would make sense to do this if we were aiming to be a catch-all library for graph-based ML models for QSPR, but that's not our goal here and those libraries already exist (a small aside: the sheer number of competing libraries/frameworks for this class of problem is indicative of the challenges associated with making a truly user-friendly and performant package). Moreover, many of our users are not experimenting with a zoo of graph-based models and are happy to stick with simply modifying the D-MPNN of Chemprop as their graph-based model option. In rewriting the package, we want to adhere as closely as possibly to the original, high-level organization of the original code (taking many liberties with respect to newly improved modularization).

However, all of this is to say that we're not opposed to anyone else pursuing one of the two options above. In fact, the newly revised object model of v2 really is not that far from playing nicely with PyG or DGL. I'm happy to eat a shoe and be proven wrong if it turns out that reimplementing Chemprop using one of those libraries further improves the speed and usability of the library. Thanks again for bringing this up, and let me know what you think.

best,
david

[^1]: https://pubs.acs.org/doi/10.1021/acs.jcim.9b00237

**Comment by mefortunato** [comment]
Hi @davidegraff, thanks for your answer. I wouldn't want you all to take on the developmental burden of managing high-level model compatibility with an architecture zoo, only to enable experimentation by us, the end users, by adopting a standard already adopted by the GNN research community. I believe the original chemprop paper was very powerful because it showed a direct comparison between fixed descriptors and learned descriptors, and provided software to enable us to repeat the experiment ourselves. Likewise, it would be very powerful to show the benefit of the D-MPNN architecture over other encoders to generate learned descriptors - but I can't really argue with your philosophical stance.

Regardless, I'll push back a little on the speed argument. You can still make use of your efficiencies in featurization to generate a `DGLGraph` directly from your `MolGraph` data class if you don't want to adopt the featurization infrastructure in dgllife, with minimal impact to computational performance. You can then leverage all of DGL's [graph API](https://docs.dgl.ai/api/python/dgl.DGLGraph.html). Here's some pseudo code:

```
g = MolGraphFeaturizer()(Chem.MolFromSmiles(<smiles>))
d = dgl.graph((g.edge_index[0], g.edge_index[1]))
d.ndata['h'] = torch.Tensor(g.V)
d.edata['e'] = torch.Tensor(g.E)
```

Having features easily accessible as pytorch tensors has proved immensely convenient when integrating with attribution packages like [captum](https://captum.ai/), if you need a tangible example of improved utility. Perhaps I'm overlooking an obvious way to use attribution methods with the current data structure, but (albeit unrelated to my original question) I'd love to see an example of feature attribution using chemprop!

**Comment by davidegraff** [comment]
I don't think it's too much work to assess the DMPNN of chemprop relative to other property prediction algorithms--the only work you might have to do is use one additional package in your benchmarking, but it's really not that much code:
```python
smis: list[str]
ys: np.ndarray
split_data: Callable[[Sequence], tuple[Sequence, Sequence, Sequence]

mp = BondMessagePassing()
agg = SumAggregation()
ffn = RegressionFFN()
mpnn = MPNN(mp, agg, ffn)
datapoints = [MoleculeDatapoint.from_smi(smi, y) for smi, y in zip(smis, ys)]
F = MolGraphFeaturizer()
train, val, test = [MoleculeDataset(split, F) for split in split_data(datapoints)
scaler = train.normalize_targets()
val.normalize_targets(scaler)
test.normalize_targets(scaler)
train_loader, val_loader, test_loader = [MolGraphDataLoader(split) for split in [train, val, test]]
trainer = pl.Trainer(devices=1, max_epochs=50)
trainer.fit(mpnn, train_loader, val_loader)
# do something with 'test'
```
I get that it's not a satisfying answer to your point about evaluating a model zoo, but no library (DGL, PyG, etc.) contains all the models you want to test, so you're already learning multiple frameworks and ours is hardly a framework as opposed to just native PyTorch objects (with some PyTorch Lightning packaged on top to limit boilerplate).

Per the second point, we're really not trying to build a catch-all DMPNN library by integrating _all_ possible graph operations. To the extent that a user is comfortable writing a model in one of those frameworks, then it's not much of a leap to simply wrap our current modules inside a compatible interface. That is to say, it's not hard to go chemprop $\to$ {DGL, PyG, ...}, and there's not much of an appetite to go in the opposite direction (i.e., write Chemprop using one of those backend libraries) for the reasons I mentioned above. As it stands, a `BatchMolGraph` is essentially a `torch_geomeric.Data` object with the attributes renamed
```python
smi = ["c1ccccc1", "CCCC"]
mols = [Chem.MolFromSmiles(smi) for smi in smis]
F = MolGraphFeaturizer()
mgs = [F(mol) for for in mols]
bmg = BatchMolGraph(mgs)
bmg
# BatchMolGraph(V=..., E=..., edge_index=..., rev_edge_index=..., batch=...)
torch.is_tensor(bmg.V)
# True
torch.is_tensor(bmg.E)
# True
bmg.batch
# torch.tensor([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])
bmg.to("cuda")
bmg.V.device
# device(type='cuda')
```
I have to admit I've not used `captum` in my own work, but it doesn't seem like it would be too much of a stretch to get it to work with the current data model given that the features are already accessible as tensors of the `BatchMolGraph` object

**Comment by mefortunato** [comment]
Thanks for your perspective. I certainly agree v2 being more pythonic makes any custom experiment significantly easier. Just wanted to propose the idea to reduce technical debt, but I can appreciate the decision to stick with custom implementations in place of adding a dependency. Looking forward to the v2 release!
