### ISSUE TITLE
`chemprop` Web Prediction Interface Removed

### ISSUE THREAD

**Issue by euhruska** [chemprop/chemprop#515]
the link to the web prediction interface seems to be broken: [http://chemprop.csail.mit.edu/](http://chemprop.csail.mit.edu/)

**Comment by kevingreenman** [comment]
We have decided to remove support for the web interface in chemprop v2.0, so this probably will not be fixed.

**Comment by JacksonBurns** [comment]
@kevingreenman if the site is currently down and we are not adding it to v2, should we officially remove the web page now? I think it would be better than leaving the page up as-is.

**Comment by kevingreenman** [comment]
@JacksonBurns yeah, maybe not a bad idea. I'm currently trying to see how difficult it is to get it back up and running temporarily (it was easy to restart it when it went down last year, but it seems like there are some extra hurdles now). Also worth mentioning is that the website was where the pretrained models for the Cell paper and COVID work were hosted (see #255), so regardless of whether we take it down now or in a few months, we should talk to the authors of those papers to have them set up a Zenodo or some alternative way of storing the models long-term

**Comment by kevingreenman** [comment]
Okay, I figured out that the website went offline on May 1, 2023 because the OS its virtual machine was running on (Ubuntu 18.04.2) was no longer supported by CSAIL as of that date. That's why the restart process from before isn't working.

**Comment by kevingreenman** [comment]
I think restarting the website will require creating a new custom [image](https://tig.csail.mit.edu/shared-computing/open-stack/images/) with a supported OS (Ubuntu 22.04 or Ubuntu 20.04) and then starting a new [instance](https://tig.csail.mit.edu/shared-computing/open-stack/instances/) from that image. I'll email CSAIL about how to do this.

**Comment by kevingreenman** [comment]
Note (from @JacksonBurns): if we decide to keep the website running as a demo of the v1 code after we no longer maintain v1, we should add a big banner to the website noting that v1 is no longer maintained, and pointing the user to the v2 code

- [ ] add banner to website

**Comment by Evert-Homan** [comment]
Hi,

Will there still be support in v2 for running a local version of the web site/server?

Thanks/Evert

**Comment by kevingreenman** [comment]
> Hi,
> 
> 
> 
> Will there still be support in v2 for running a local version of the web site/server?
> 
> 
> 
> Thanks/Evert

No

**Comment by Evert-Homan** [comment]
Hmmm, that's too bad.

Thanks/Evert

**Comment by kevingreenman** [comment]
We apologize if the web interface is something you use often. We chose to remove it for a few reasons:

- The companies that fund the development of the software don't use the web tool
- It's a burden on the developers to also have to update the web tool when we add new features. Because of this, the web code hasn't been touched for quite some time despite the fact that we've added many new features in the rest of the code.
- The web tool forces us to carry additional dependencies that make it difficult to use chemprop on Windows OS.

If we were to continue supporting a web tool, we would probably put it in a separate repo. However, we don't think we have the bandwidth to maintain the separate tool right now.

The web tool will remain available to you in the version 1 releases, so you're welcome to continue using it for what you've been using it for.

**Comment by JacksonBurns** [comment]
I'm slightly modifying the title and will leave a note here for any newcomers.

# Summary:
 - `chemprop` v1 supports running a web interface for prediction
 - previously, there was an MIT-hosted website that hosted an instance of this website
 - this website has __gone down and will not be restored__
 - `chemprop` v2 will not support a web interface natively; the feature will not be removed from v1
