### ISSUE TITLE
[QUESTION]: Fragments/salts in data sets

### ISSUE THREAD

**Issue by Evert-Homan** [chemprop/chemprop#531]
Hi,

I noted that some of the included data sets, e.g. Tox21 and BBBP, contain fragmented smiles (most are presumably salts), but have not read anywhere that these are stripped before generating descriptors by Chemprop. Would that not be a good idea, or do you believe it does not affect the outcome of the models?

I always strip off salts, so just want to make other users aware of this.

Thanks/Evert

**Comment by kevingreenman** [comment]
These are not stripped. I've seen some cases where the identity of the counterion (e.g. Cl vs. Br) doesn't make a large difference in the predictions, but removing it entirely does make a big difference. I think the decision of whether to strip salts should be left up to the user, because in some cases it might not be the desired behavior.
