### ISSUE TITLE
Default number of epochs should depend on class balance

### ISSUE THREAD

**Issue by simonaxelrod** [chemprop/chemprop#55]
I believe that the `class_balance` option leads to epochs that sample <img src="https://render.githubusercontent.com/render/math?math=2\cdot \mathrm{min}(\mathrm{num_pos}, \mathrm{num_neg})"> data points per epoch, where <img src="https://render.githubusercontent.com/render/math?math=\mathrm{num_pos}"> is the number of molecules with label 1 and <img src="https://render.githubusercontent.com/render/math?math=\mathrm{num_neg}"> for label 0. This means that the points sampled per epoch is <img src="https://render.githubusercontent.com/render/math?math=\alpha = 2\cdot \mathrm{min}(\mathrm{num_pos}, \mathrm{num_neg}) / (\mathrm{num_pos} %2B   \mathrm{num_neg})"> times smaller than in the non-balanced case. I think it makes sense to scale the default number of epochs by <img src="https://render.githubusercontent.com/render/math?math=1/\alpha"> when using `class_balance`.

**Comment by swansonk14** [comment]
Hi @simonaxelrod, that's an interesting idea! I think it makes sense, but I think it would be better to keep the number of epochs set to the value specified by the user rather than changing it under the hood in a manner that they might not realize. So for that reason I'm not going to make this change, but I would certainly encourage you to experiment with manually changing the number of epochs depending on the class balance where appropriate.

**Comment by simonaxelrod** [comment]
Sounds good, that makes sense! Thanks for getting back to me.

Simon
