### ISSUE TITLE
[QUESTION]: Interpret property_id

### ISSUE THREAD

**Issue by soulios** [chemprop/chemprop#555]
Hey, I am trying to use the interpret function and I stumbled across the argument "property_id".  If I understand correctly, in the example of a multilabel classification like tox21.csv, setting the property_id=1 would provide interpretations for the first target in the csv of the trained model? 
If so, when you set the id to an index higher than the number of the columns, the function should throw an error, right?
If that's not the case what property_id represents?

**Comment by kevingreenman** [comment]
You are correct. If you were to set `property_id` to an index higher than the number of the columns, I would expect the function to throw an error on [this line](https://github.com/chemprop/chemprop/blob/514e3b5ab2078c5b0085b9855f4ee80471ee8dc0/chemprop/interpret.py#L312) because the index would be out of range. Please reopen this issue and let us know if you see different behavior from this.

**Comment by soulios** [comment]
```
    def scoring_function(smiles: List[str]) -> List[float]:
        return chemprop_model(smiles)[:, args.property_id - 1]

    C_PUCT = args.c_puct
    MIN_ATOMS = args.min_atoms

    all_smiles = get_smiles(path=args.data_path, smiles_columns=args.smiles_columns)
    header = get_header(path=args.data_path)

    property_name = header[args.property_id] if len(header) > args.property_id else 'score'
    print(f'smiles,{property_name},rationale,rationale_score')
```

In the line of property_name shouldn't it be also be header[args.property_id -1] assuming that the first column is also smiles?
I would suggest changing the argument property_id to property_name altogether for clarity and readability.
Also saving to a csv would be helpful. I can open a PR if needed.                                                                                                                     

```
header = get_header(path=args.data_path)

    try:
        property_index = header.index(args.property_name)
    except ValueError:
        raise ValueError(f"Property name '{args.property_name}' not found in the dataset header.")

    def scoring_function(smiles: List[str]) -> List[float]:
        # Adjusted to use the found property_index
        return chemprop_model(smiles)[:, property_index]
```

**Comment by kevingreenman** [comment]
The default for `property_id` is 1 rather than 0, so that would skip the SMILES column. But I see what you're saying that it could be confusing. We are no longer accepting PRs for chemprop v1, but we will keep this in mind when the interpret function is added to v2. I agree that saving to a CSV would be helpful.
