### ISSUE TITLE
[BUG]: Slower CPU performance with recent environment

### ISSUE THREAD

**Issue by cjmcgill** [chemprop/chemprop#565]
**Describe the bug**
A recently built environment for Chemprop performed *much* more slowly when running with CPU resources. I have not done further troubleshooting to drill down on what exactly is the cause yet but it's an alarming slowdown so I am posting. My CPU utilization on all cores also nearly maxes out, while it runs very slowly. 

**Example(s)**
I have compared the performance of the recent build (python 3.11.6) versus one rebuilt with an older environment (python 3.9.18). The performance on a minimal training job (5 epochs, esol) was vastly different. The relative times were 2m42s and 0m17s, respectively. A big difference. This occurs even when I set `num_workers 0` which should knock out some multithreading behavior issues.

```
python $chemprop_dir/train.py \
--dataset_type regression \
--data_path ESOL.csv \
--save_dir $save_dir/ \
--seed 0 \
--pytorch_seed ${seed} \
--aggregation norm \
--depth 4 \
--ffn_num_layers 2 \
--hidden_size 1000 \
--ffn_hidden_size 1000 \
--epochs 5 \
--save_smiles_splits
```
Screenshot of the max CPU load
![Screenshot from 2023-12-20 16-59-08](https://github.com/chemprop/chemprop/assets/44245643/c36a9d6c-fb32-4a06-909a-715e822b4d2f)

**Expected behavior**
I would expect the training behavior between the versions to be roughly equivalent. And for the CPU load to be low except for a few cores.

**Environment**
OS: Ubuntu-22.04.3
New Environment:
[new_environment.txt](https://github.com/chemprop/chemprop/files/13732991/new_environment.txt)
Old rebuilt environment:
[old_environment.txt](https://github.com/chemprop/chemprop/files/13732993/old_environment.txt)

**Comment by davidegraff** [comment]
Interesting. Can you possibly benchmark the dataloading speed between the two environments? Just iterating through once should give a sense of whether the slowdown is coming from the model or the transform pipeline

**Comment by cjmcgill** [comment]
The initial data loading before training starts right, not batching behavior during training?

**Comment by davidegraff** [comment]
I mean iterating through your dataloader. Not data preprocessing/structuring

**Comment by JacksonBurns** [comment]
@cjmcgill is this comparing chemprop v1 to v1, v1 to v2, or v2 to v2? I wasn't aware you could even build v1 in an environment with Python 3.9 or newer.

**Comment by cjmcgill** [comment]
@JacksonBurns It's v1 versus v1. v1 doesn't run tests on python 3.9 or newer, but there's nothing about the environment yml that bars using the new stuff and if you don't specifically change it then it will.

**Comment by kevingreenman** [comment]
I agree with limiting the Python version. Since we don't plan on maintaining v1 after the release of v2, I think not limiting the Python version could open us up to additional problems beyond this one. If the slower performance is not present in `python<=3.8`, we should open a PR to limit the version in the environment file, and that will be enough to close this issue.

**Comment by davidegraff** [comment]
I'm not opposed to limiting v1 python support. Why can't we allow up to 3.9 if @cjmcgill seems to have no problems with though?

**Comment by JacksonBurns** [comment]
Since tests don't run on 3.9 we can't verify that something isn't going wrong (though anecdotally it seems fine).

FWIW 3.9 is also going to be dropped by major packages like Numpy soon (see [here](https://numpy.org/neps/nep-0029-deprecation_policy.html#:~:text=On%20Apr%2005%2C%202024%20drop%20support%20for%20Python%203.9%20(initially%20released%20on%20Oct%2005%2C%202020))) (like 3.8 already has), so putting in the effort to support it here would buy us only a few extra months of dependency updates from the community.
