### ISSUE TITLE
[FEATURE] [v2] support arbitrary lightning loggers

### ISSUE THREAD

**Issue by davidegraff** [chemprop/chemprop#594]
per #591, it would be a nice feature to support all of the [loggers](https://lightning.ai/docs/pytorch/stable/extensions/logging.html) that are supported in pytorch lightning via the `chemprop train` CLI. We would probably need to abstract out this process into a via some custom `build_logger : LoggerConfig -> lightning.pytorch.loggers.Logger` function, where a `LoggerConfig` is some dataclass that holds the recipe for which `Logger` to build and how to initialize it.

> [!NOTE]
> The concept of a `Logger` is different from _whether a user even wants to log_. This is controlled via the `log_every_n_steps` flag in the `lightning.Trainer` object

A practical outline might be:
1. abstract [this line](https://github.com/chemprop/chemprop/blob/79d971138a1456f21356216ac0aadd92a39ef6a4/chemprop/cli/train.py#L660) into a function
2. refactor the function to accept a `LoggerConfig` dataclass that stores the `TensorboardLogger` arguments in a structured format
3. expose a new `LoggerConfig` argument via the CLI

One thing we should be careful is exposing _too many_ arguments via the CLI. We currently have over **90** options via the CLI, and even organizing these into a single config can be overwhelming. IMO, we should move "less critical" option groups into their own _separate_ config files.

**Comment by KnathanM** [comment]
I like the idea of moving some option groups into separate config files, probably the ones that we think will be used less often. I can bring that up in our next meeting.

**Comment by JacksonBurns** [comment]
From a cursory glance through the GitHub issues, having searched for 'logger', it seems like no one asked for a different logger type in v1. This is possibly YAGNI? I welcome discussion on this though

**Comment by davidegraff** [comment]
I feel like this is mostly for industry users. I like to use WandB and not store training logs locally, but industry users will need a license to use that or their org might already be using MLFlow for instance. I've previously just hacked it using a local fork, but probably not a good model to ask our users to do that

**Comment by KnathanM** [comment]
I wonder if we can close this issue. Our dev team has less bandwidth for additions to the CLI as we have had people graduate this summer, so I think we need to narrow our scope to focus on bringing v2 to feature parity with v1 and adding [MLPDS](https://mlpds.mit.edu) requested features (since they fund at least my development of Chemprop). 

I enjoy having Chemprop use the `lightning` framework because of the many things we get "for free" like using different loggers. I think it is reasonable to expect users to read the `lightning` docs and write their own scripts to make use of these `lightning` features. Our main responsibility is to show how to properly set up the model, dataset, and featurizers because those are provided by our code.

**Comment by davidegraff** [comment]
That’s a fair point that I’m happy to accept. Feel free to close!
