### ISSUE TITLE
[TODO]: Add paper references

### ISSUE THREAD

**Issue by Oceanusity** [chemprop/chemprop#598]
Hello, thanks for providing this wonderful packages, and provide multiple useful APIs.

As a kindly reminder, would you mind adding some paper reference for some implemented functions? For example, the interpret part is similar to [SubgraphX](https://arxiv.org/abs/2102.05152), would you mind adding the reference or add some comments to illustrate it?

https://chemprop.readthedocs.io/en/latest/_modules/chemprop/interpret.html

**Comment by kevingreenman** [comment]
Hi @Oceanusity, our interpret function was primarily written 4 years ago (as shown in the [git blame](https://github.com/chemprop/chemprop/blame/master/chemprop/interpret.py)) based on @wengong-jin's ICML 2020 paper ["Multi-Objective Molecule Generation using Interpretable Substructures"](https://arxiv.org/abs/2002.03244) (original code for that paper is [here](https://github.com/wengong-jin/multiobj-rationale/tree/master)). Since our code predates and thus was not based on SubgraphX, I don't think it would be appropriate for us to cite it. Please let me know if I'm misunderstanding something. 

I can add a note to our README indicating the reference to @wengong-jin's paper for the interpret function. Our Read the Docs pages unfortunately haven't been updated in quite some time, and we don't plan to update them before the imminent release of [Chemprop v2](https://github.com/chemprop/chemprop/issues/517), so the README is currently the best place to look for the most up-to-date information on Chemprop v1 releases.

If you have feedback on other parts of the code that you think should reference prior work, please let us know.

**Comment by Oceanusity** [comment]
Thank you for your comments. If you wouldn't mind, could you please append a note to Wengong-Jin's paper? I intend to close this issue as my concerns have been addressed.  Thanks.

**Comment by kevingreenman** [comment]
I just [added](https://github.com/chemprop/chemprop/commit/54bd7b376960ed34f5b678dc00f5fc3f13e87f50) the reference to Wengong's paper to our README.

I'm not sure what you mean by "append a note to Wengong-Jin's paper". Could you please clarify?

**Comment by Oceanusity** [comment]
I just update the content in the reply. Thanks.
