### ISSUE TITLE
MPI support?

### ISSUE THREAD

**Issue by Jiang-Lu-CAS** [chemprop/chemprop#60]
Hi, can chemprop use mpi to run parallely? I tried in my grid but it run the same task for several time.

**Comment by swansonk14** [comment]
Hi @Jiang-Lu-CAS, I haven't tried using MPI myself and I'm not particularly familiar with it so I'm not totally sure if it's possible, but it would be great if we could make it work. Do you think you could provide a few more details about your setup so that I can try to reproduce your problem and see if I can get it to work?
