### ISSUE TITLE
[Question] SMILES validation

### ISSUE THREAD

**Issue by nathanmlim** [chemprop/chemprop#61]
How is Chemprop checking or validating the input SMILES strings? 

I'm getting warnings that 970 of my SMILES are invalid but when I check my SMILES through RDkit using `Chem.MolFromSmiles()` no SMILES are returning as invalid?

**Comment by swansonk14** [comment]
Hi @nathanmlim, we currently filter using the function `filter_invalid_smiles`: https://github.com/chemprop/chemprop/blob/master/chemprop/data/utils.py#L92. Essentially it checks to see if the SMILES is an empty string, if RDKit fails to process the molecule, or if there are no heavy atoms.

When you use `Chem.MolFromSmiles()`, do you check to see whether the returned molecule object is `None` or not? RDKit doesn't explicitly complain about invalid molecules, but it will give you a `None` instead of an RDKit Mol object and that's how you can tell whether the SMILES are invalid or not.
