### ISSUE TITLE
can't find in pypi

### ISSUE THREAD

**Issue by jkwang93** [chemprop/chemprop#64]
I'm try to install chemprop by pip install chemprop, but can't find this package.

**Comment by swansonk14** [comment]
Hi @jkwang93, I apologize for the issue. I added the pip installation instructions to the README before chemprop was pushed ty PyPi. I've now release chemprop on PyPi so you should be able to run `pip install chemprop`. Also, please don't forget to install rdkit and descriptastorus inside your conda environment by running `conda install -c conda-forge rdkit` and `pip install git+https://github.com/bp-kelley/descriptastorus` since they can't be installed during pip installation.
