### ISSUE TITLE
Tautomers in Chemprop interpretation

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#641]
Hello,
I was wondering how chemprop interpretation deals with the possible tautomers.

Thank you
Best Regards
Soo

**Comment by kevingreenman** [comment]
Since the input to chemprop is a SMILES string that is converted to a single, fixed graph structure, there is no way to account for tautomers or other phenomena that are not represented by a fixed 2D graph. The only way to teach a chemprop model that two tautomers have the same (or different) property is to include both tautomers with their corresponding labels in your training data.
