### ISSUE TITLE
Why we need index 0 as zero-padding for the tensors of atom features and bond features?

### ISSUE THREAD

**Issue by tingweidaniel** [chemprop/chemprop#65]
Just wondering, why the script (line 203~205) in _featurization.py_ need index 0 as **zero-padding**? Does any specific case (or molecules) may crash when we remove zero-padding of the tensors of atom features and bond features?

Thank you so much!

**Comment by chao1224** [comment]
@tingweidaniel 
Because in [line 229](https://github.com/chemprop/chemprop/blob/master/chemprop/features/featurization.py#L229), a special index 0 is needed for padding.

**Comment by swansonk14** [comment]
@tingweidaniel thank you for the question and @chao1224 thank you for the great answer! To add a bit more detail, each row of `a2b` contains all the indices for bonds that are adjacent to a given atom. Each atom may have a different number of bonds that it is adjacent to, but since `a2b` is a tensor, it needs to have a fixed size. Therefore, `a2b` is padded with zero indices to indicate that there are no additional bonds that the atom is adjacent to. Since these indices are then used to sum the adjacent bond features, there needs to be a 0 pad in `f_atoms` and `f_bonds` so that this zero index access these zero features and therefore do not affect the overall sum of adjacent bond features. I hope this makes sense and please let me know if you have any other questions!
