### ISSUE TITLE
[QUESTION]: V2: Why is w_t a `nn.Parameter`?

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#657]
Why are the task weights [set](https://github.com/chemprop/chemprop/blob/v2/dev/chemprop/models/model.py#L97) as an `nn.Parameter`? I think this [sets](https://pytorch.org/docs/stable/generated/torch.nn.parameter.Parameter.html) `requires_grad = True` for the weights, which aren't learnable parameters.

To my understanding we should register task weights as a buffer instead. But also we haven't run into a problem so far with it as a Parameter.

**Comment by davidegraff** [comment]
The second argument sets `requires_grad=False`. While I'm sure there _are_ differences between the two, a non-learnable parameter and a buffer are functionally the same in most cases, which is why it hasn't created any problems for us. This line is a remnant of when I didn't know about `register_buffer`, but I agree with you that it should be moved over (and possible renamed `w_t` -> `task_weights`).
