### ISSUE TITLE
[BUG]: Chemprop v2 CLI training is not deterministic even when setting random seeds manually

### ISSUE THREAD

**Issue by jjacobgreen** [chemprop/chemprop#755]
**Describe the bug**
Running training on the same dataset multiple times gives very different test MSEs. This happens both when using the default random seeds and when manually specifying the random seeds manually.

**Example(s)**
Dataset used was ESOL from MoleculeNet (available [here](https://moleculenet.org/datasets-1)). 

I ran the following command twice in a row, changing the name of the `output-dir` each time:
```
chemprop train --data-path delaney-processed.csv --task-type regression --output-dir delaney_seed42_run1 --smiles-columns smiles --target-columns "measured log solubility in mols per litre" --data-seed 42 --pytorch-seed 42
```
Output 1: 
```
test/mse            0.47709617352924577
```
Output 2:
```
test/mse            0.5599762683237152
```

**Expected behavior**
Using the same training command on the same dataset mutiple times with the same random seed (the default, 0, or a custom one, e.g. 42) should train approximately the same model with very similar test MSEs and test set predictions very close to each other.

**Error Stack Trace**
N/A

**Screenshots**
N/A

**Environment**
- python 3.11.8
- package versions: 
    - chemprop                  2.0.0rc1 
    - torch                     2.2.1
    - torch_geometric           2.5.2
    - torch_scatter             2.1.2+pt22cu121
    - torchmetrics              1.3.2
    - torchvision               0.17.1
    - pytest                   7.4.4
- OS
    - Ubuntu 22.04.4 LTS (Jammy Jellyfish) - inside Docker container

**Checklist**
- [X] all dependencies are satisifed: `conda list` shows the packages listed in the `README`
- [ ] the unit tests are working: `pytest -v` reports no errors
    - `1 failed, 642 passed, 11 skipped, 231 warnings in 783.13s (0:13:03)`
     - One failure: `tests/cli/test_cli_regression_mol.py::test_freeze_model FAILED` - possibly relevant but not sure
```
>       assert torch.equal(
            trained_model.message_passing.W_o.weight, frzn_model.message_passing.W_o.weight
        )
E       RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument other in method wrapper_CUDA__equal)
```

**Additional context**
- I relase this is still an rc version, so this might be an issue you're already aware of or is planned for future releases - apologies if so!
- Test suite was run by cloning the repo, checking out at the `2.0.0-rc-1` tag and running the test suite in the same environment I was running the CLI in.
- I believe there's a simple fix: the pytorch lightning `Trainer` object just needs the argument `deterministic=True` passed to it on this line: https://github.com/chemprop/chemprop/blob/4a1c1f206a3d12d3f9df0f8248a3350f47bafb89/chemprop/cli/train.py#L731
    - I briefly tested this and it seems to fix the issue - happy to open a PR myself!
- Please let me know if you need any more information - thanks for the awesome library

**Comment by davidegraff** [comment]
thanks for the investigation! the `deterministic` flag is a good find, but it [may make code slower](https://lightning.ai/docs/pytorch/stable/common/trainer.html#deterministic). I wonder what the other devs think, but my current thinking is that if a user sets the `--pytorch-seed` argument, then we should set it to be `True`. For example:

```python
determinstic = args.pytorch_seed is not None
# ...
trainer = pl.Trainer(
    # ...
    deterministic=deterministic
)
```
The issue with this proposal though is that, for some reason, we always set the `--pytorch-seed` as 0 by default:
https://github.com/chemprop/chemprop/blob/6f2d69018377e3e29f16325b2faa625d06f43191/chemprop/cli/train.py#L442-L447

It seems that this so that we can seed the individual ensemble members here:
https://github.com/chemprop/chemprop/blob/6f2d69018377e3e29f16325b2faa625d06f43191/chemprop/cli/train.py#L715

but I'm not sure if the same can't be accomplished by just changing that line to:

```python
if args.pytorch_seed is None:
    seed = torch.seed()
    deterministic = False
else:
    seed = args.pytorch_seed + model_idx
    deterministic = True
torch.manual_seed(seed)
# ...
trainer = pl.Trainer(
    # ...
    deterministic=deterministic
)
```
The main difference with this change is that:
1. training is non-deterministic by default. IMO this is preferable because in the current implementation it's not possible to get _truly_ random training results, i.e., a user would have to supply a pseudorandomly generated seed to override the default of 0
2.  ensemble members no longer share consecutive seeds in the default case. This doesn't really mean anything as there's no significance to consecutive random seeds.

**Comment by JacksonBurns** [comment]
I'm surprised that the `deterministic` option fixes this. This large of a difference would make think it's a bug, but alas.

That unit test failure is OK. The model checkpoints were generated on CPU, if you run the tests on a machine with a GPU some data will end up there instead of the CPU and pytorch errors out. It's a bug we should probably fix later, but not an urgent concern and not related to this.

**Comment by jjacobgreen** [comment]
Thanks for the speedy responses on this. I was also suprised at how large the differences were - I reran the training a few times on some other datasets as well and to me there always seemed to be a reasonably large difference. That being said, it's not a huge dataset (~1000 SMILES), and I just used the default number of training epochs (50), so I imagine it's likely the example provided is at the larger end of differences.

Personally, I'm a fan of the proposed solution. I suppose that it's not actually that large a change, given that training is already effectively non-deterministic by default. That being said, more evidence might be required to be sure that adding the `deterministic` argument does in fact fix the issue.

(Good to know regarding the CPU/GPU tensor difference - should have mentioned that I'm runnig a machine with a GPU attached!)

**Comment by KnathanM** [comment]
If I understand correctly there are three sources of randomness when making a chemprop model:
1. The data split
2. The model parameter initialization
3. The steps taken by `pl.Trainer`

We currently have CLI flags to control 1 and 2. Either we need to add a flag for the third, or make it dependent on 1 and 2.
I agree that the default should be not-deterministic. This is a change from v1, but if it is not the default, it is hard to get random training. 

It is possible a user could want to initialize model parameters reproducibly but then train not deterministically if they are testing how training hparams (learning rate, etc.) affect model performance and training time and want to have all models start the same. But this seems to be an edge case and in any event this is possible by loading a initialized model from a checkpoint. 

I agree with David to tie deterministic training to setting a pytorch seed. I see cases where the user would fix the dataset seed but still want random training like if they were doing ensembling manually or want to try different hyperparameters on the same split.
