### ISSUE TITLE
[TODO]: Run tests on M1

### ISSUE THREAD

**Issue by KnathanM** [chemprop/chemprop#776]
**Notes**
#711 showed that our code couldn't run on an M1 MBP. #761 fixed this by explicitly using float32's instead of float64's. Perhaps we should run our tests on an [M1 image](https://github.com/actions/runner-images/issues/9254) so that future changes don't accidentally reintroduce float64 usage.

**Comment by JacksonBurns** [comment]
The CI currently specifies `macos-latest` which resolves to the `macos-14` image running on M1, see [the GitHub docs](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).

We didn't catch this earlier because our tests must have just missed it.

**Comment by KnathanM** [comment]
Thanks for pointing that out. Our tests have been working on `macos-latest` even with using some float64's. Do you know why our tests worked while #711 had the issue? Is that something we can reproduce in the GitHub tests so it isn't missed in the future?

**Comment by JacksonBurns** [comment]
I looked back at the issue and realized that it's actually because the user was running using MPS ([see PyTorch docs](https://pytorch.org/docs/stable/notes/mps.html)), basically the apple version of CUDA/ROCM acceleration. Our unit tests probably would have found this if anyone had run them on a machine using MPS-pytorch. The github actions runners  don't have GPUs [unless we upgrade to this](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners) so we have no way to catch it right now. But really it's a pretty small problem - we can probably safely ignore this and just fix these issues as they arise.

**Comment by JacksonBurns** [comment]
Re-closing - running on M1 macs is not possible ATM and the upstream solution is well beyond our reach, see the linked comment above this one.
