### ISSUE TITLE
interpret with --feature_path

### ISSUE THREAD

**Issue by oolzroo** [chemprop/chemprop#79]
I run chemprop with --feature_path to incorporate my own features into the model. However, I found when I run interpret.py, it asked me to add --feature_generator because it detected that I have other features apart from the chemical smiles. I try to use --feature_path when running interpret since my features are not generated from the --feature_generator but it seems it doesn't take --feature_path. 
Any suggestions? Thanks.

**Comment by swansonk14** [comment]
Hi @oolzroo, the reason that `--features_path` is not allowed when using `interpret.py` is that the algorithm needs to run the model not just on the whole molecule but on fragments of the molecule. It might be possible to adapt the `interpret.py` code to accept pre-computed features of molecule fragments, but right now that's not possible. So instead `interpret.py` currently only allows `--features_generator` so that it can dynamically compute new molecule-level features on the fragments of the molecule.

Is there any way you can turn your features into a features generator? Chemprop includes a template showing how to create a custom features generator (https://github.com/chemprop/chemprop/blob/master/chemprop/features/features_generators.py#L141), so would that be possible for your use case or can you only use pre-computed features saved to a file?
