### ISSUE TITLE
[TODO]: Add example notebook(s) for interoperability between chemprop and other libraries

### ISSUE THREAD

**Issue by kevingreenman** [chemprop/chemprop#804]
**Notes**
At the MLPDS meeting, we got a question about how one could use chemprop featurizers with other packages (e.g. DGL or sklearn), such that they could use the same featurizer across all of their models. If possible, it would be nice to add an example notebook of this to highlight the modularity of v2.

**Comment by KnathanM** [comment]
#1063 showed how to use the chemprop featurizer with DGL and with torch geometric. We chose to not show how to integrate chemprop with sklearn because the chemprop featurizer produces a graph while sklearn operates on vectors. The chemprop message passing layer can produce a vector, but should be trained first. As this issue was about the featurizer and not about combining chemprop models with other models, #1063 didn't show how to do this.
