### ISSUE TITLE
[v2 BUG]: readthedocs latest doesn't successfully build from main branch

### ISSUE THREAD

**Issue by Rhys-McAlister** [chemprop/chemprop#828]
As title implies, the url to the docs in the new readme links to the old docs.

**Comment by JacksonBurns** [comment]
You have to change from `latest` to `v2/dev`: https://chemprop.readthedocs.io/en/v2-dev/

This will be the default in a day or so once we do the official release of v2.

**Comment by kevingreenman** [comment]
This should have been fixed by updating our Read the Docs settings ("Admin" > "Settings" > "Default branch") from `---------` to `main`, but the build [fails](https://beta.readthedocs.org/projects/chemprop/builds/24161094/). I made a separate version of the docs that points to `main`, and that build [succeeds](https://beta.readthedocs.org/projects/chemprop/builds/24161210/), even though it's the exact same code as the "latest" version that points to `main`. I can't figure out how to fix this right now. I've temporarily updated the links in our README and release notes to point to https://chemprop.readthedocs.io/en/main/ instead of https://chemprop.readthedocs.io/en/latest/ (which still shows the last successful build from `master`). 

The only issue with this is that if someone tries to go to https://chemprop.readthedocs.io/, it will redirect to "latest". The same goes for redirects from https://chemprop.csail.mit.edu/.

The relevant RTD issue is here: https://github.com/readthedocs/readthedocs.org/issues/7907

**Comment by kevingreenman** [comment]
I just filled out the support form at https://readthedocs.org/support/ since we haven't heard back on our [issue](https://github.com/readthedocs/readthedocs.org/issues/11321) in a couple weeks. If we still don't hear back, it might be worth temporarily upgrading our readthedocs membership (looks like the lowest tier is $5/month), because this allows us to set a priority level with our support requests, which would hopefully lead to faster responses.

**Comment by kevingreenman** [comment]
As noted [here](https://github.com/readthedocs/readthedocs.org/issues/11321#issuecomment-2123425294), the problem seems to be the [line](https://github.com/chemprop/chemprop/blob/9437523e8791790c7109293b89fcc018c3bfa00c/docs/source/conf.py#L42) `autoapi_ignore = ["*test*", "*cli*"]` in our `docs/source/conf.py`. The pattern `*test*` is too broad because it matches to `latest`, which is the name of the build. Thus, we get the error message `No source files found in: /home/docs/checkouts/readthedocs.org/user_builds/chemprop/checkouts/latest`.

**Comment by kevingreenman** [comment]
This was fixed in the most recent [build](https://beta.readthedocs.org/projects/chemprop/builds/24463014/) by changing from `autoapi_ignore = ["*test*", "*cli*"]` to `autoapi_ignore = ["*/tests/*", "*/cli/*"]`.
