### ISSUE TITLE
[v1 BUG]: OOM when make prediction

### ISSUE THREAD

**Issue by TH1052638958** [chemprop/chemprop#867]
**Describe the bug**
The memory used when I use a trained model to do prediction is larger than that I train first and then do prediction in the same python script .

**Example(s)**

**Expected behavior**
```
#code
import chemprop
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.offsetbox import `AnchoredText`
from sklearn.metrics import mean_absolute_error, mean_squared_error
import argparse

parser = argparse.ArgumentParser(description='test')
parser.add_argument('--epochs',type=str,default='100')
parser.add_argument('--depth',type=str,default='3')
parser.add_argument('--dir-exp',type=str)
parser.add_argument('--epochs',type=int)
parser.add_argument('--batch-size',type=int)
parser.add_argument('--init-train',type=bool,default=True)
args0 = parser.parse_args()

if(args0.init_train):
    arguments_train = [
                '--data_path', 'datasets/traindata.csv',
                '--dataset_type', 'regression',
                '--split_type', 'random',
                '--split_sizes', '0.8','0.2', '0.0',
                '--save_dir', args0.dir_exp,
                '--epochs', str(args0.epochs),
                '--batch_size', str(args0.batch_size),
                '--log_frequency', "1",
                '--save_smiles_splits',
                '--dropout', '0.2',
                '--extra_metrics', 'r2',
                '--ffn_hidden_size', '1000',
                '--ffn_num_layers', '3',
                '--depth', '5',
                '--final_lr', '0.00001',
                '--features_generator', 'rdkit_2d_normalized',
                '--no_features_scaling',
                '--loss_function', 'mve'
            ]

    args = chemprop.args.TrainArgs().parse_args(arguments_train)
    args.num_workers = 0
    mean_score, std_score = chemprop.train.cross_validate(args=args, train_func=chemprop.train.run_training)
arguments_pred = [
            '--test_path', '/dev/null',
            '--preds_path', '/dev/null',
            '--checkpoint_dir',args.dir_exp,
            '--uncertainty_method', 'dropout',
            '--batch_size', '20000',
            '--features_generator', 'rdkit_2d_normalized',
            '--no_features_scaling'
        ]
args_pred = chemprop.args.PredictArgs().parse_args(arguments_pred)
args_pred.num_workers = 0
df_smiles = pd.read_csv('data/Ampc_data_500k.csv')
data_rest = df_smiles['smiles'].values[:, np.newaxis].tolist()[:500000]
pred_mu, pred_sigma = chemprop.train.make_predictions(args=args_pred, smiles=data_rest, return_uncertainty=True)
```

The train dataset containing 20k smiles and prediction data contining 2M smiles.
When I set `argo.init_train=True`,the memory used is 28G at prediction part.But when I set `argo.init_train=False`,the memory used is 80G at prediction part.
I wonder what's wrong with it and how I can load a trained model to make prediction.

**Comment by JacksonBurns** [comment]
Hi @TH1052638958 thanks for the bug report. Without the training data it will be difficult to try and reproduce this locally. Just from the code, I would guess that:
 - `num_workers` is being ignored during predict, resulting in higher memory usage (you could check CPU usage to verify this)
 - `batch_size` could also be being ignored
 - there is a very difficult to handle bug elsewhere

The 'easy' solution is to batch your predictions manually, i.e. load `df_smiles` in fourths and call predict. This _should_ reduce the memory usage to a point where you can run prediction again.

I'll add that we have also released Chemprop v2 which should be less buggy than v1. We can also fix bugs in v2 (if the bug is even discovered here, we will not implement a fix due to time constraints). I encourage you to re-write this using Chemprop v2 to see if the issue persists.
