### ISSUE TITLE
Transfer Learning and Few shot learning in chemprop

### ISSUE THREAD

**Issue by SoodabehGhaffari** [chemprop/chemprop#868]
Hello,
I have a pre-trained model built using chemprop and used the transfer learning methods in chemprop (based on the pre-trained model) for related tasks. I also tried to build the models for related tasks from scratch (without transfer learning). My intuition was that the models from transfer learning should outperform the models built from scratch. However, this is not always the case. I was wondering if there is any rational behind that or there is any paper which compared the models from transfer learning with models from scratch using chemprop.

Also, I was wondering if there is a method in Chemprop for few-shoting learning. One of my tasks only has 8 positive data points among around 75000 data points.

I would appreciate it if you help me with any suggestions/papers in this regard.

Best Regards,
Soo

**Comment by JacksonBurns** [comment]
> My intuition was that the models from transfer learning should outperform the models built from scratch. [...] I was wondering if there is any rational behind that or there is any paper which compared the models from transfer learning with models from scratch using chemprop.

The goal for transfer learning is that they _should_, but this really get into the 'art-not-a-science' of machine learning. Transfer learning doesn't always improve performance, since there are cases where the learned weights can be anti-correlated to your new target of interest and the fine-tuning has to first overcome these before learning its own. Ultimately if it doesn't work, it's best to either skip it or pre-train on something else.

@kevingreenman @shihchengli do either of you know of any papers which have directly compared Chemprop models trained either directly on a dataset or with transfer learning?

> One of my tasks only has 8 positive data points among around 75000 data points.

This is so few positive examples that you are well into the range of [anomaly detection](https://en.wikipedia.org/wiki/Anomaly_detection) - this is an order of magnitude lower positive rate than famous [credit card fraud](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud) dataset. I think it is nearly impossible for Chemprop (or any method, really) to learn this target.

**Comment by SoodabehGhaffari** [comment]
Thank you for the response.
I noticed there was a typo in my previous email. The correct version is
"One of my tasks only has *68* positive data points among around 75000 data
points." Do you think if chemprop can learn this target now?

Thanks
Best Regards
Soo

**Comment by shihchengli** [comment]
What I have noticed for papers comparing both Chemprop trained from scratch and with transfer learning are the following two papers:
1. https://doi.org/10.1016/j.cej.2021.129307
2. https://pubs.acs.org/doi/10.1021/acs.jpca.2c02614

**Comment by JacksonBurns** [comment]
Thanks @shihchengli! @SoodabehGhaffari those papers should be enough to get you started - if you run into a technical issue with running transfer learning, please let us know.

I realized I didn't answer your questions about few shot learning earlier. We don't have any built in support for few shot learning and have no plans to add it.

> The correct version is "One of my tasks only has *68* positive data points among around 75000 data points." Do you think if chemprop can learn this target now?

No.
