### ISSUE TITLE
[v1 QUESTION]: Can I use randomized SMILES to augment my active assay test data? 

### ISSUE THREAD

**Issue by BIOBRICK** [chemprop/chemprop#892]
**What are you trying to do?**
Can I use **randomized SMILES** to augment my active assay test data? 

**Previous attempts**
I have tried chemprop 1.7.1 to build a model based on my bioassay data. However, I found the data is extremely unbalanced(only 1.9% molecules marked as active.) So I used randomized SMILES to balance the data. Every molecule generate <= 15 randomized SMILES in my attempet. I noticed very good model performance after the augment(AUC =0.95, PRAUC=0.97,F1=0.96).

But I found the **tanimoto similary** between randomized SMILES equels 1 with the source molecule. So maybe such method has no different with just repeating the source molecules? I think the chemprop utilize the structure graph information from SMILES, so maybe such method is actually randomized SMILES can't be used in such graph/structural based method?

Any help will be useful for me. Many tks!

**Screenshots**

**Comment by JacksonBurns** [comment]
Hi @BIOBRICK this is theoretical question and not much Chemprop can actually handle, but we can try and provide some input.

First, when you input multiple SMILES strings that encode the same structure they are _usually_ identical to Chemprop. This is because the very basic atom and bond information that Chemprop uses in the initial embeddings (atomic weight, order, etc) doesn't change for multiple valid SMILES of the same molecule. @akshatzalte can tell you about some of the edge cases where this isn't the case, especially when dealing with multiple resonance structures, but in general this shouldn't be a problem.

Second, the randomized SMILES is generally only used for generative modeling, from what I can see from a quick search. The reason that the tanimoto similarity is 1 is because these SMILES encode the _same_ molecule - the purpose of randomized SMILES is to allow generative models to learn the entire syntax of the SMILES 'language' by simply exposing the model to multiple valid ways of encoding something. You are correct that it really won't do anything for this purpose.

Finally - by using randomized SMILES here, you are basically performing __oversampling__ but in a not especially rigorous way. I invite you to read the documentation from [imbalanced learn](https://imbalanced-learn.org/stable/over_sampling.html) as a starting point for learning more about oversampling. You should ideally be randomly duplicating your source data (without using randomized SMILES, which doesn't do anything for us) with replacement _just until_ you achieve a class balance. You may also want to look at the more advanced techniques offered in that package, which should work better.

I'm not totally sure why the performance now looks nearly perfect, but I suspect the model has just memorized the dataset or the class balance has actually been thrown off in the opposite direction. This is something you will have to evaluate for yourself after looking at these sampling methods.

**Comment by BIOBRICK** [comment]
> Hi @BIOBRICK this is theoretical question and not much Chemprop can actually handle, but we can try and provide some input.
> 
> First, when you input multiple SMILES strings that encode the same structure they are _usually_ identical to Chemprop. This is because the very basic atom and bond information that Chemprop uses in the initial embeddings (atomic weight, order, etc) doesn't change for multiple valid SMILES of the same molecule. @akshatzalte can tell you about some of the edge cases where this isn't the case, especially when dealing with multiple resonance structures, but in general this shouldn't be a problem.
> 
> Second, the randomized SMILES is generally only used for generative modeling, from what I can see from a quick search. The reason that the tanimoto similarity is 1 is because these SMILES encode the _same_ molecule - the purpose of randomized SMILES is to allow generative models to learn the entire syntax of the SMILES 'language' by simply exposing the model to multiple valid ways of encoding something. You are correct that it really won't do anything for this purpose.
> 
> Finally - by using randomized SMILES here, you are basically performing **oversampling** but in a not especially rigorous way. I invite you to read the documentation from [imbalanced learn](https://imbalanced-learn.org/stable/over_sampling.html) as a starting point for learning more about oversampling. You should ideally be randomly duplicating your source data (without using randomized SMILES, which doesn't do anything for us) with replacement _just until_ you achieve a class balance. You may also want to look at the more advanced techniques offered in that package, which should work better.
> 
> I'm not totally sure why the performance now looks nearly perfect, but I suspect the model has just memorized the dataset or the class balance has actually been thrown off in the opposite direction. This is something you will have to evaluate for yourself after looking at these sampling methods.

Many Thanks. I thought it carefully and found that actually I'm really just doing oversampling. I should have thought this earlier. About my model performance, I believe that's because I added morgan fingerprint during training and I actually get an overfitting model. After I removed morgan fingerprint, I get metrics around 0.8, however, you are right, I still can't say that this is "not" and overfitting model. I think unbalanced data is a really huge challenge, escapelly in small-molecule area becaues we can't add noise or "random" sample in our datasets. I guess that's the reason in many paper the authors do not quite care about the model performance.
Anyway many thanks for your help!
